### ISSUE TITLE
Impossible to inherit class with self aggregation

### ISSUE THREAD

**Issue by vladimir-tikhonov** [AssemblyScript/assemblyscript#1024]
Wasn't able to came up with a meaningful title for this one :|

Link to webassembly studio: https://webassembly.studio/?f=m1p23xigjr

Code:
```typescript
export class RandomObject {
    public child: Child|null = null;
}

export class Parent {
    public randomObject: RandomObject|null = null;
}

export class Child extends Parent { }

new Child();
```

Proper stack trace:
```
ERROR: AssertionError: assertion failed
    at t.assert (~assemblyscript/std/portable/index.js:184:9)
    at assert (~assemblyscript/src/program.ts:3675:3)
    at new registerConcreteElement (~assemblyscript/src/program.ts:3407:5)
    at _.resolveClass (~assemblyscript/src/resolver.ts:2783:16)
    at _.resolveClass [as resolveClassInclTypeArguments] (~assemblyscript/src/resolver.ts:3031:17)
    at d.resolveClassInclTypeArguments [as compileNewExpression] (~assemblyscript/src/compiler.ts:7806:37)
    at d.compileNewExpression [as compileExpression] (~assemblyscript/src/compiler.ts:2891:21)
    at d.compileExpression [as compileExpressionStatement] (~assemblyscript/src/compiler.ts:1996:17)
    at d.compileExpressionStatement [as compileStatement] (~assemblyscript/src/compiler.ts:1732:21)
    at d.compileStatement [as compileTopLevelStatement] (~assemblyscript/src/compiler.ts:1697:25)
```

**Comment by MaxGraey** [comment]
> Wasn't able to came up with a meaningful title for this one :|
Perhaps it could be call "Impossible inherit class with self aggregation"

**Comment by vladimir-tikhonov** [comment]
@MaxGraey good catch! Seems like I was too exited after extracting this from ~10kloc of code and decided to give up simplifying it too quickly :)
