### ISSUE TITLE
TypedArray forEach method have an unknown error

### ISSUE THREAD

**Issue by echoloyuk** [AssemblyScript/assemblyscript#1051]
here is my demo code:

```
export function sum(arr: Uint32Array): i32 {
  let a: i32 = 0;
  arr.forEach((value: i32) => {
    a += value;
  });
  return a;
}
```

as the code sample means, function sum will return the array's sum. I use forEach to get the sum to param: a, and then return. but when i execute `asc assembly/index.ts -b build/untouched.wasm -t build/untouched.wat --sourceMap --validate --debug` command and then gets an error, with useless detail. I still cannot know whats going on?

The error in terminal is:

```
as1@1.0.0 asbuild:untouched /Users/mac/myProject/assemblyscript/as1
> asc assembly/index.ts -b build/untouched.wasm -t build/untouched.wat --sourceMap --validate --debug

ERROR: AssertionError: assertion failed
    at t.assert (/Users/mac/myProject/assemblyscript/as1/node_modules/assemblyscript/dist/assemblyscript.js:1:556244)
    at m.compileBinaryExpression (/Users/mac/myProject/assemblyscript/as1/node_modules/assemblyscript/dist/assemblyscript.js:1:258503)
    at m.compileExpression (/Users/mac/myProject/assemblyscript/as1/node_modules/assemblyscript/dist/assemblyscript.js:1:245392)
    at m.compileExpressionStatement (/Users/mac/myProject/assemblyscript/as1/node_modules/assemblyscript/dist/assemblyscript.js:1:234125)
    at m.compileStatement (/Users/mac/myProject/assemblyscript/as1/node_modules/assemblyscript/dist/assemblyscript.js:1:230467)
    at m.compileStatements (/Users/mac/myProject/assemblyscript/as1/node_modules/assemblyscript/dist/assemblyscript.js:1:231414)
    at m.compileFunctionBody (/Users/mac/myProject/assemblyscript/as1/node_modules/assemblyscript/dist/assemblyscript.js:1:220994)
    at m.compileFunction (/Users/mac/myProject/assemblyscript/as1/node_modules/assemblyscript/dist/assemblyscript.js:1:223519)
    at m.compileFunctionExpression (/Users/mac/myProject/assemblyscript/as1/node_modules/assemblyscript/dist/assemblyscript.js:1:305108)
    at m.compileExpression (/Users/mac/myProject/assemblyscript/as1/node_modules/assemblyscript/dist/assemblyscript.js:1:245670)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! as1@1.0.0 asbuild:untouched: `asc assembly/index.ts -b build/untouched.wasm -t build/untouched.wat --sourceMap --validate --debug`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the as1@1.0.0 asbuild:untouched script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mac/.npm/_logs/2020-01-10T16_49_30_104Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! as1@1.0.0 asbuild: `npm run asbuild:untouched && npm run asbuild:optimized`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the as1@1.0.0 asbuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mac/.npm/_logs/2020-01-10T16_49_30_130Z-debug.log
```

**Comment by MaxGraey** [comment]
AssermblyScript doesn't support closures yet

**Comment by dcodeIO** [comment]
Strange though that this is still hitting an assertion, will investigate.

**Comment by MaxGraey** [comment]
Yeah, after #955 it should emit error properly. Hmm

**Comment by echoloyuk** [comment]
> AssermblyScript doesn't support closures yet

Is there any recommend ways? Now I change to:

```
export function sum(arr: Uint32Array): i32 {
  let a: i32 = 0;
  arr.forEach(function(value: i32) {
    a += value;
  });
  return a;
}
```

And the error still the same

**Comment by dcodeIO** [comment]
Seems this affects compound expressions like `+=` only since these don't do the common denominator check that would otherwise yield a proper error.

**Comment by MaxGraey** [comment]
Because it still capture `a` variable in lexical environment.
Workarounds:
1) use for/while loop
2) use global for `a`:
```ts
let a: u32 = 0;
export function sum(arr: Uint32Array): u32 {
  arr.forEach(value => { a += value });
  return a;
}
```
3) use reduce:
```ts
export function sum(arr: Uint32Array): u32 {
  return arr.reduce((a, b) => a + b, 0);
}
```

**Comment by echoloyuk** [comment]
Ohhhhh~~~ I got that. "doesn't support closures" means I cannot use any ref params outside forEach in the loop function. Looks little wierd~~.

**Comment by echoloyuk** [comment]
> Because it still capture `a` variable in lexical environment.
> Workarounds:
> 
> 1. using for/while loop
> 2. using global for `a`:
> 
> ```ts
> let a: u32 = 0;
> export function sum(arr: Uint32Array): u32 {
>   arr.forEach(value => { a += value });
>   return a;
> }
> ```
> 
> 1. using reduce:
> 
> ```ts
> export function sum(arr: Uint32Array): u32 {
>   return arr.reduce((a, b) => a + b, 0 as u32);
> }
> ```

Thank you so much~~~, finally I change to the for loop. it works.

**Comment by dcodeIO** [comment]
Half a fix for at least the assertion in https://github.com/AssemblyScript/assemblyscript/pull/1046, but would probably be better to have a `never` type to handle that properly.
