### ISSUE TITLE
"memory access out of bounds" when assigning a string property

### ISSUE THREAD

**Issue by miracle2k** [AssemblyScript/assemblyscript#1101]
AS: 

```typescript
export class Box {
    constructor(public s: string) {}
}
```

JS:

```js
const fs = require("fs")
const loader = require("@assemblyscript/loader")
const myImports = { }
const myModule = loader.instantiateSync(
  fs.readFileSync("optimized.wasm"),
  myImports
)


const { Box, __allocString, __retain, __release } = myModule

const str = __retain(__allocString("my string"))
const box = new Box(str);
box.s = str;
```

Output:

```
RuntimeError: memory access out of bounds
    at wasm-function[19]:5
    at wasm-function[13]:13
    at wasm-function[16]:27
    at curr.<computed>.set [as s] (/Users/michael/Development/mine/wasmbind/test/node_modules/@assemblyscript/loader/index.js:378:36)
    at Object.<anonymous> (/Users/michael/Development/mine/wasmbind/test/test.js:15:7)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
```

The error occurs in the last line when the `box.s` assignment happens.

loader "0.9.1"

$ npx assemblyscript -v
Version 0.9.1

**Comment by dcodeIO** [comment]
The problem here seems to be in the generated setter function, that utilizes a flow but shouldn't since it doesn't have one, leading to a confusion of locals, in turn leading to invalid loads.

**Comment by dcodeIO** [comment]
The PR linked above should fix this, that is if there isn't more going on. Let me know :)

**Comment by dcodeIO** [comment]
Closing the issue with the PR being merged. Feel free to reopen if there's still something going haywire :)
