### ISSUE TITLE
Failing with "TypeError: this is not a typed array."

### ISSUE THREAD

**Issue by ColinEberhardt** [AssemblyScript/assemblyscript#114]
I have installed AssemblyScript

~~~
npm i assemblyscript -g
~~~

Created a simple 'hello world' example, `hello.ts`:

~~~
export function test(): i32 {
  return 42;
}
~~~

However, compilation fails as follows:

~~~
$ asc hello.ts -o hello.wasm
initialization took 59.369 ms
compilation took 9.638 ms

/Users/colineberhardt/.nvm/versions/node/v6.10.0/lib/node_modules/assemblyscript/node_modules/binaryen/index.js:26
typeof module&&(module.exports=a);process.on("uncaughtException",function(e){if(!(e instanceof ha))throw e;});a.inspect=function(){return"[Emscripten Module object]"}}else if(La)a.print||(a.print=print),"undefined"!=typeof printErr&&(a.printErr=printErr),a.read="undefined"!=typeof read?read:function(){throw"no read() available";},a.readBinary=function(e){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(e));e=read(e,"binary");v("object"===typeof e);return e},"undefined"!=typeof scriptArgs?
                                                                                                   ^

TypeError: this is not a typed array.
    at Function.from (native)
    at writeBinary (/Users/colineberhardt/.nvm/versions/node/v6.10.0/lib/node_modules/assemblyscript/bin/asc.js:209:23)
    at Object.main (/Users/colineberhardt/.nvm/versions/node/v6.10.0/lib/node_modules/assemblyscript/bin/asc.js:162:5)
    at Object.<anonymous> (/Users/colineberhardt/.nvm/versions/node/v6.10.0/lib/node_modules/assemblyscript/bin/asc:2:21)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)

~~~

**Comment by dcodeIO** [comment]
Seems to be caused by `Buffer.from` [here](https://github.com/AssemblyScript/assemblyscript/blob/master/bin/asc.js#L209). Not exactly sure what type of array `emitBinary` emits across node versions. Possible fix could be:

````js
output.write(Buffer.from(new Uint8Array(wasmModule.emitBinary())), end);
```

**Comment by ColinEberhardt** [comment]
Just returning to this issue, and frustratingly cannot reproduce! I'll re-open if it happens again or I can provide more context.

**Comment by dcodeIO** [comment]
One more thought: I encountered errors like these when also using emscripten / emsdk because of the bundled node v4.something that it adds to path.
