### ISSUE TITLE
`AssertionError: assertion failed` on build

### ISSUE THREAD

**Issue by kbjr** [AssemblyScript/assemblyscript#1178]
Pretty much what the title says. When attempting to build, I'm getting the following error. I'm not really sure what to do with this output.

```
ERROR: AssertionError: assertion failed
    at assert (/.../node_modules/assemblyscript/dist/webpack:/assemblyscript/std/portable/index.js:184:9)
    at k.setType (/.../node_modules/assemblyscript/dist/webpack:/assemblyscript/src/program.ts:2398:5)
    at m.compileGlobal (/.../node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:963:16)
    at m.compileTopLevelStatement (/.../node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:1860:20)
    at m.compileFile (/.../node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:892:12)
    at m.compileFileByPath (/.../node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:872:10)
    at m.compileTopLevelStatement (/.../node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:1886:14)
    at m.compileFile (/.../node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:892:12)
    at m.compileFileByPath (/.../node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:872:10)
    at m.compileTopLevelStatement (/.../node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:1886:14)
```

What is this error message trying to tell me?

**Comment by kbjr** [comment]
I got another one

```
ERROR: AssertionError: assertion failed
    at assert (/.../node_modules/assemblyscript/dist/webpack:/assemblyscript/std/portable/index.js:184:9)
    at u.canOverflow (/.../node_modules/assemblyscript/dist/webpack:/assemblyscript/src/flow.ts:1087:5)
    at m.compileReturnedExpression (/.../node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:3400:15)
    at m.compileFunctionBody (/.../node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:1386:23)
    at m.compileFunction (/.../node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:1304:12)
    at m.compileFunctionExpression (/.../node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:7697:12)
    at m.compileExpression (/.../node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:3299:21)
    at m.compileGlobal (/.../node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:952:25)
    at m.compileTopLevelStatement (/.../node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:1860:20)
    at m.compileTopLevelStatement (/.../node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:1845:18)
```

**Comment by MaxGraey** [comment]
could you provide minimal example code? All this assert messages not helpful

**Comment by kbjr** [comment]
I wish I could, but that's kind of what the problem is. The error doesn't give me a file or line number, so I don't know what I'm trying to reproduce.

**Comment by MaxGraey** [comment]
Such assert  errors are internal compiler stuff, so it provide only stack traces and without conext (actual code) it hard to figure out what exactly happening

**Comment by MaxGraey** [comment]
If you codebase is large you could use divide and conquer approach. Just  comment half of code and try to compile, and repeat this halving as much as need

**Comment by pitust** [comment]
I got a small program demonstrating this:
```typescript
function main(): number {
    var a: void = null;
    return 0;
}
main();
```

**Comment by pitust** [comment]
@kbjr What you have looks like this:
(function () {
return <something>;
});

**Comment by MaxGraey** [comment]
In this case we already issue for this: https://github.com/AssemblyScript/assemblyscript/issues/558

**Comment by MaxGraey** [comment]
> (function () {
  return ;
});

Print:
```
ERROR TS1110: Type expected.

 (function () {
                   ^
```
Which is normal behaviour due to AS require type notions for return values. Please read docs

**Comment by pitust** [comment]
No, not that. inside the return expression, there is something which breaks the compiler. But there should be some more info about these asserts.

**Comment by MaxGraey** [comment]
@pitust Plz create separate issue for this if you can create a minimal example

**Comment by pitust** [comment]
There could be a print for where is the assertion caused, pthat would make it a lot simpler.
