### ISSUE TITLE
asc's --converge argument is broken

### ISSUE THREAD

**Issue by Feavy** [AssemblyScript/assemblyscript#1248]
Hello,

AssemblyScript Compiler throws an error when using the `--converge` argument:

````
PS C:\Users\quent\Documents\Projets_Javascript\AssemblyScript-Test> yarn asprod
yarn run v1.21.1
$ asc assembly/index.ts -b build/build.wasm --optimize --converge
TypeError: Cannot read property 'length' of undefined
    at C:\Users\quent\Documents\Projets_Javascript\AssemblyScript-Test\node_modules\assemblyscript\dist\assemblyscript.js:7:132929
    at E (C:\Users\quent\Documents\Projets_Javascript\AssemblyScript-Test\node_modules\assemblyscript\dist\assemblyscript.js:7:133115)
    at c.toBinary (C:\Users\quent\Documents\Projets_Javascript\AssemblyScript-Test\node_modules\assemblyscript\dist\assemblyscript.js:7:124717)
    at C:\Users\quent\Documents\Projets_Javascript\AssemblyScript-Test\node_modules\assemblyscript\cli\asc.js:836:25
    at measure (C:\Users\quent\Documents\Projets_Javascript\AssemblyScript-Test\node_modules\assemblyscript\cli\asc.js:1103:3)
    at Object.main (C:\Users\quent\Documents\Projets_Javascript\AssemblyScript-Test\node_modules\assemblyscript\cli\asc.js:832:25)
    at C:\Users\quent\Documents\Projets_Javascript\AssemblyScript-Test\node_modules\assemblyscript\bin\asc:21:47
TypeError: Cannot read property 'length' of undefined
    at C:\Users\quent\Documents\Projets_Javascript\AssemblyScript-Test\node_modules\assemblyscript\dist\assemblyscript.js:7:132929
    at E (C:\Users\quent\Documents\Projets_Javascript\AssemblyScript-Test\node_modules\assemblyscript\dist\assemblyscript.js:7:133115)
    at c.toBinary (C:\Users\quent\Documents\Projets_Javascript\AssemblyScript-Test\node_modules\assemblyscript\dist\assemblyscript.js:7:124717)
    at C:\Users\quent\Documents\Projets_Javascript\AssemblyScript-Test\node_modules\assemblyscript\cli\asc.js:836:25
    at measure (C:\Users\quent\Documents\Projets_Javascript\AssemblyScript-Test\node_modules\assemblyscript\cli\asc.js:1103:3)
    at Object.main (C:\Users\quent\Documents\Projets_Javascript\AssemblyScript-Test\node_modules\assemblyscript\cli\asc.js:832:25)
    at C:\Users\quent\Documents\Projets_Javascript\AssemblyScript-Test\node_modules\assemblyscript\bin\asc:21:47

C:\Users\quent\Documents\Projets_Javascript\AssemblyScript-Test\node_modules\binaryen\index.js:18
function u(b){if(a.onAbort)a.onAbort(b);x(b);A(b);ta=!0;throw"abort("+b+"). Build with -s ASSERTIONS=1 for more info.";}var v=null,Va="data:application/octet-stream;base64,",Wa,Xa;
                                                        ^
abort(TypeError: Cannot read property 'length' of undefined). Build with -s ASSERTIONS=1 for more info.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
````

**Comment by dcodeIO** [comment]
Can confirm, something's broken there
