### ISSUE TITLE
[HELP] NPM package

### ISSUE THREAD

**Issue by bakasura980** [AssemblyScript/assemblyscript#1315]
Hello team,

I am trying to make my code as npm package. But when I import it into another project and build that project, it always throws `Build with -s ASSERTIONS=1 for more info.` 

Is there any documentation of how to do a standard npm package?

**Comment by dcodeIO** [comment]
This looks like a Binaryen error, typically indicating invalid codegen. Could you paste the entire message, even though it's probably cryptic?

**Comment by MaxGraey** [comment]
Could you provide more error info? It seems like it error relate to Binaryen. Also how project you npm project structure looks like?

**Comment by bakasura980** [comment]
<img width="346" alt="Screen Shot 2020-06-08 at 16 50 23" src="https://user-images.githubusercontent.com/8825116/84038175-437bad00-a9a8-11ea-9d66-d47365a3a45e.png">

**Comment by bakasura980** [comment]
The message ```
AssertionError: assertion failed
    at t.assert (/Users/lyubo/Projects/Polkadot/ScaleCodec/test-scale/node_modules/assemblyscript/dist/assemblyscript.js:7:611418)
    at f.initialize (/Users/lyubo/Projects/Polkadot/ScaleCodec/test-scale/node_modules/assemblyscript/dist/assemblyscript.js:7:72408)
    at Object.t.initializeProgram (/Users/lyubo/Projects/Polkadot/ScaleCodec/test-scale/node_modules/assemblyscript/dist/assemblyscript.js:7:630467)
    at stats.initializeTime.measure (/Users/lyubo/Projects/Polkadot/ScaleCodec/test-scale/node_modules/assemblyscript/cli/asc.js:617:20)
    at measure (/Users/lyubo/Projects/Polkadot/ScaleCodec/test-scale/node_modules/assemblyscript/cli/asc.js:966:3)
    at Object.main (/Users/lyubo/Projects/Polkadot/ScaleCodec/test-scale/node_modules/assemblyscript/cli/asc.js:616:27)
    at asc.ready.then (/Users/lyubo/Projects/Polkadot/ScaleCodec/test-scale/node_modules/assemblyscript/bin/asc:21:47)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at startup (internal/bootstrap/node.js:283:19) message: 'assertion failed' }
{ AssertionError: assertion failed
    at t.assert (/Users/lyubo/Projects/Polkadot/ScaleCodec/test-scale/node_modules/assemblyscript/dist/assemblyscript.js:7:611418)
    at f.initialize (/Users/lyubo/Projects/Polkadot/ScaleCodec/test-scale/node_modules/assemblyscript/dist/assemblyscript.js:7:72408)
    at Object.t.initializeProgram (/Users/lyubo/Projects/Polkadot/ScaleCodec/test-scale/node_modules/assemblyscript/dist/assemblyscript.js:7:630467)
    at stats.initializeTime.measure (/Users/lyubo/Projects/Polkadot/ScaleCodec/test-scale/node_modules/assemblyscript/cli/asc.js:617:20)
    at measure (/Users/lyubo/Projects/Polkadot/ScaleCodec/test-scale/node_modules/assemblyscript/cli/asc.js:966:3)
    at Object.main (/Users/lyubo/Projects/Polkadot/ScaleCodec/test-scale/node_modules/assemblyscript/cli/asc.js:616:27)
    at asc.ready.then (/Users/lyubo/Projects/Polkadot/ScaleCodec/test-scale/node_modules/assemblyscript/bin/asc:21:47)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at startup (internal/bootstrap/node.js:283:19) message: 'assertion failed' }
/Users/lyubo/Projects/Polkadot/ScaleCodec/test-scale/node_modules/binaryen/index.js:57
function r(b){if(a.onAbort)a.onAbort(b);t(b);v(b);Aa=!0;throw new za("abort("+b+"). Build with -s ASSERTIONS=1 for more info.");}function Ya(b){var f=Za;return String.prototype.startsWith?b.startsWith(f):0===b.indexOf(f)}var Za="data:application/octet-stream;base64,",$a="";if(!Ya($a)){var ab=$a;$a=a.locateFile?a.locateFile(ab,p):p+ab}var bb,cb;Ma.push({$:function(){db()}});var J={},eb=[];
                                                        ^

Error: abort(AssertionError: assertion failed). Build with -s ASSERTIONS=1 for more info.```

**Comment by dcodeIO** [comment]
Seems to happen in `Program#initialize`. Has a couple `assert` there involving imports and exports, so my guess would be that there's something wrong with an import or an export referencing a wrong file or similar. Hitting the assertion is a bug in the first place, though, and a fix would probably show a better error but not magically make it work.

How are you importing the other module? And what are you exporting from it?

**Comment by bakasura980** [comment]
@MaxGraey @dcodeIO , We found the problem, it works excellent with assemblyscript@0.9.4. Trying to build it with v0.10.0 throws

**Comment by willemneal** [comment]
Can you link the project?

**Comment by MaxGraey** [comment]
@willemneal I guess it [here](https://github.com/LimeChain/as-scale-codec)

**Comment by Daniel-K-Ivanov** [comment]
Hi @MaxGraey @willemneal and thanks for your help.
Have you managed to find the bug? Do you have more information on it or progress? 
Is there something that you think we can do to mitigate the problem?

We are trying to bump up the version of AS to the latest one because there is support for interfaces and virtual overloading (as @MaxGraey pointed out in another PR).
