### ISSUE TITLE
Failure compiling: `abort(AssertionError: assertion failed`

### ISSUE THREAD

**Issue by james2mid** [AssemblyScript/assemblyscript#1469]
Hi guys, I'm getting the following log when trying to compile and it doesn't make much sense to me.

```
> wasm-example@0.0.0 asbuild:dev /Users/james/code/wasm-example
> asc assembly/index.ts --target debug

Error [AssertionError]: assertion failed
    at t.assert (/Users/james/code/wasm-example/node_modules/assemblyscript/dist/assemblyscript.js:7:635183)
    at y.finalizeVirtualStub (/Users/james/code/wasm-example/node_modules/assemblyscript/dist/assemblyscript.js:7:479249)
    at y.compile (/Users/james/code/wasm-example/node_modules/assemblyscript/dist/assemblyscript.js:7:382854)
    at Object.t.compile (/Users/james/code/wasm-example/node_modules/assemblyscript/dist/assemblyscript.js:7:655800)
    at /Users/james/code/wasm-example/node_modules/assemblyscript/cli/asc.js:713:29
    at measure (/Users/james/code/wasm-example/node_modules/assemblyscript/cli/asc.js:1101:3)
    at Object.main (/Users/james/code/wasm-example/node_modules/assemblyscript/cli/asc.js:712:24)
    at /Users/james/code/wasm-example/node_modules/assemblyscript/bin/asc:21:47
/Users/james/code/wasm-example/node_modules/binaryen/index.js:57
function q(b){if(a.onAbort)a.onAbort(b);v(b);Aa=!0;throw new za("abort("+b+"). Build with -s ASSERTIONS=1 for more info.");}function Xa(b){var d=Ya;return String.prototype.startsWith?b.startsWith(d):0===b.indexOf(d)}var Ya="data:application/octet-stream;base64,",Za="";if(!Xa(Za)){var $a=Za;Za=a.locateFile?a.locateFile($a,p):p+$a}var ab,bb;La.push({Rs:function(){cb()}});
                                                   ^

Error: abort(AssertionError: assertion failed). Build with -s ASSERTIONS=1 for more info.
    at process.q (/Users/james/code/wasm-example/node_modules/binaryen/index.js:57:58)
    at process.emit (events.js:314:20)
    at processPromiseRejections (internal/process/promises.js:245:33)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
```

The `index.ts` AS code is as follows. I've narrowed it down to being **the `store` calls which cause the issue** (I'm trying to follow the [WASM by Example guide](https://wasmbyexample.dev/examples/reading-and-writing-graphics/reading-and-writing-graphics.assemblyscript.en-us.html) and make it more readable — their code compiles btw).

```ts
const BOARD_SIZE: i32 = 20

interface RGBA {
  r: i8
  g: i8
  b: i8
  a: i8
}

export const BOARD_BUFFER_PTR: i32 = 0
export const BOARD_BUFFER_SIZE: i32 = BOARD_SIZE * BOARD_SIZE * 4

export function generate (
  dark: RGBA,
  light: RGBA,
): void {

  // Loop over each square on the board
  for (let x: i32 = 0; x < BOARD_SIZE; x++) {
    for (let y: i32 = 0; x < BOARD_SIZE; y++) {
      let isDark: boolean = true

      if (y % 2 === 0) {
        isDark = false
      }

      if (x % 2 === 0) {
        isDark = !isDark
      }

      const value: RGBA = isDark ? dark : light

      const squareNumber = y * BOARD_SIZE + x
      const ptrSquareRgba = BOARD_BUFFER_PTR + squareNumber * 4

      store<u8>(ptrSquareRgba + 0, value.r)
      store<u8>(ptrSquareRgba + 1, value.g)
      store<u8>(ptrSquareRgba + 2, value.b)
      store<u8>(ptrSquareRgba + 3, value.a)
    }
  }
}
```

**Comment by MaxGraey** [comment]
Problem part:
Your problem part:
```ts
interface RGBA {
  r: i8
  g: i8
  b: i8
  a: i8
}
```
interface types still has limited support.
Btw @dcodeIO could be ipmlement [this](https://github.com/AssemblyScript/assemblyscript/issues/299) for now?

**Comment by jriehl** [comment]
I don't think this is so stale.  I hit this problem all the time.  My reproduction is publicly available at: https://github.com/jriehl/sandbox/tree/master/assemblyscript/issue1469

Running the build outputs the following:

```shell
% npm run asbuild

> issue1635@1.0.0 asbuild
> npm run asbuild:untouched && npm run asbuild:optimized


> issue1635@1.0.0 asbuild:untouched
> asc assembly/index.ts --target debug

Error [AssertionError]: assertion failed
    at assert (/Users/jon/git/sandbox/assemblyscript/issue1469/node_modules/assemblyscript/dist/webpack:/assemblyscript/std/portable/index.js:199:9)
    at finalizeVirtualStub (/Users/jon/git/sandbox/assemblyscript/issue1469/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:6820:30)
    at f.compile (/Users/jon/git/sandbox/assemblyscript/issue1469/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:540:14)
    at Object.t.compile (/Users/jon/git/sandbox/assemblyscript/issue1469/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/index.ts:264:32)
    at /Users/jon/git/sandbox/assemblyscript/issue1469/node_modules/assemblyscript/cli/asc.js:810:29
    at measure (/Users/jon/git/sandbox/assemblyscript/issue1469/node_modules/assemblyscript/cli/asc.js:1242:3)
    at Object.main (/Users/jon/git/sandbox/assemblyscript/issue1469/node_modules/assemblyscript/cli/asc.js:809:24)
    at /Users/jon/git/sandbox/assemblyscript/issue1469/node_modules/assemblyscript/bin/asc:19:47

/Users/jon/git/sandbox/assemblyscript/issue1469/node_modules/binaryen/index.js:54
function Ka(){var b=a.preRun.shift();Fa.unshift(b)}var L=0,La=null,Ma=null;a.preloadedImages={};a.preloadedAudios={};function q(b){if(a.onAbort)a.onAbort(b);v(b);wa=!0;throw new va("abort("+b+"). Build with -s ASSERTIONS=1 for more info.");}function Na(b){var d=Oa;return String.prototype.startsWith?b.startsWith(d):0===b.indexOf(d)}var Oa="data:application/octet-stream;base64,",Pa="<<< WASM_BINARY_FILE >>>";if(!Na(Pa)){var Qa=Pa;Pa=a.locateFile?a.locateFile(Qa,p):p+Qa}
                                                                                                                                                                              ^
Error: abort(AssertionError: assertion failed). Build with -s ASSERTIONS=1 for more info.
    at process.q (/Users/jon/git/sandbox/assemblyscript/issue1469/node_modules/binaryen/index.js:54:175)
    at process.emit (node:events:378:20)
    at process.emit (/Users/jon/git/sandbox/assemblyscript/issue1469/node_modules/source-map-support/source-map-support.js:495:21)
    at emit (node:internal/process/promises:202:22)
    at processPromiseRejections (node:internal/process/promises:223:25)
    at processTicksAndRejections (node:internal/process/task_queues:95:32)
Error: exit 1
    at process.exit (/Users/jon/git/sandbox/assemblyscript/issue1469/node_modules/assemblyscript/cli/asc.js:38:25)
    at printErrorAndExit (/Users/jon/git/sandbox/assemblyscript/issue1469/node_modules/source-map-support/source-map-support.js:479:11)
    at process.emit (/Users/jon/git/sandbox/assemblyscript/issue1469/node_modules/source-map-support/source-map-support.js:491:16)
    at process._fatalException (node:internal/process/execution:163:25)
npm ERR! code 1
npm ERR! path /Users/jon/git/sandbox/assemblyscript/issue1469
npm ERR! command failed
npm ERR! command sh -c asc assembly/index.ts --target debug
```
