### ISSUE TITLE
Assertion failure when attempting to finalize a virtual stub.

### ISSUE THREAD

**Issue by jriehl** [AssemblyScript/assemblyscript#1674]
I was hoping commenting would reopen issue #1469, but no such luck.  Assuming posts to closed issues aren't given much look, so I'm opening this issue.

From my comment for #1469:

...I hit this problem all the time.  My reproduction is publicly available at: https://github.com/jriehl/sandbox/tree/master/assemblyscript/issue1469

Running the build outputs the following:

```shell
% npm run asbuild

> issue1635@1.0.0 asbuild
> npm run asbuild:untouched && npm run asbuild:optimized


> issue1635@1.0.0 asbuild:untouched
> asc assembly/index.ts --target debug

Error [AssertionError]: assertion failed
    at assert (/Users/jon/git/sandbox/assemblyscript/issue1469/node_modules/assemblyscript/dist/webpack:/assemblyscript/std/portable/index.js:199:9)
    at finalizeVirtualStub (/Users/jon/git/sandbox/assemblyscript/issue1469/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:6820:30)
    at f.compile (/Users/jon/git/sandbox/assemblyscript/issue1469/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:540:14)
    at Object.t.compile (/Users/jon/git/sandbox/assemblyscript/issue1469/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/index.ts:264:32)
    at /Users/jon/git/sandbox/assemblyscript/issue1469/node_modules/assemblyscript/cli/asc.js:810:29
    at measure (/Users/jon/git/sandbox/assemblyscript/issue1469/node_modules/assemblyscript/cli/asc.js:1242:3)
    at Object.main (/Users/jon/git/sandbox/assemblyscript/issue1469/node_modules/assemblyscript/cli/asc.js:809:24)
    at /Users/jon/git/sandbox/assemblyscript/issue1469/node_modules/assemblyscript/bin/asc:19:47

/Users/jon/git/sandbox/assemblyscript/issue1469/node_modules/binaryen/index.js:54
function Ka(){var b=a.preRun.shift();Fa.unshift(b)}var L=0,La=null,Ma=null;a.preloadedImages={};a.preloadedAudios={};function q(b){if(a.onAbort)a.onAbort(b);v(b);wa=!0;throw new va("abort("+b+"). Build with -s ASSERTIONS=1 for more info.");}function Na(b){var d=Oa;return String.prototype.startsWith?b.startsWith(d):0===b.indexOf(d)}var Oa="data:application/octet-stream;base64,",Pa="<<< WASM_BINARY_FILE >>>";if(!Na(Pa)){var Qa=Pa;Pa=a.locateFile?a.locateFile(Qa,p):p+Qa}
                                                                                                                                                                              ^
Error: abort(AssertionError: assertion failed). Build with -s ASSERTIONS=1 for more info.
    at process.q (/Users/jon/git/sandbox/assemblyscript/issue1469/node_modules/binaryen/index.js:54:175)
    at process.emit (node:events:378:20)
    at process.emit (/Users/jon/git/sandbox/assemblyscript/issue1469/node_modules/source-map-support/source-map-support.js:495:21)
    at emit (node:internal/process/promises:202:22)
    at processPromiseRejections (node:internal/process/promises:223:25)
    at processTicksAndRejections (node:internal/process/task_queues:95:32)
Error: exit 1
    at process.exit (/Users/jon/git/sandbox/assemblyscript/issue1469/node_modules/assemblyscript/cli/asc.js:38:25)
    at printErrorAndExit (/Users/jon/git/sandbox/assemblyscript/issue1469/node_modules/source-map-support/source-map-support.js:479:11)
    at process.emit (/Users/jon/git/sandbox/assemblyscript/issue1469/node_modules/source-map-support/source-map-support.js:491:16)
    at process._fatalException (node:internal/process/execution:163:25)
npm ERR! code 1
npm ERR! path /Users/jon/git/sandbox/assemblyscript/issue1469
npm ERR! command failed
npm ERR! command sh -c asc assembly/index.ts --target debug
```

_Originally posted by @jriehl in https://github.com/AssemblyScript/assemblyscript/issues/1469#issuecomment-774777676_

**Comment by MaxGraey** [comment]
It's binaryen assertion. It means happened something unexpected which not cached by frontend of compiler. Without minimal reproduction hard to tell what's happened

**Comment by jriehl** [comment]
@MaxGraey, I provided a link to my code, and it attempts to be as minimal as possible.  Does that not count?

**Comment by MaxGraey** [comment]
Now I see. The main problem in `zero` field. If you replace it to get/set property [this will repaired](https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1zcGVlZCZydW50aW1lPXN0dWIKZXhwb3J0IG5hbWVzcGFjZSBUcmVlIHsKICAgIGV4cG9ydCBjbGFzcyBOb2RlPFQ+IHsKICAgICAgICBjb25zdHJ1Y3RvcigKICAgICAgICAgICAgcHVibGljIHBheWxvYWQ6IFQsCiAgICAgICAgICAgIHB1YmxpYyBsZWZ0OiBOb2RlPFQ+IHwgbnVsbCwKICAgICAgICAgICAgcHVibGljIHJpZ2h0OiBOb2RlPFQ+IHwgbnVsbAogICAgICAgICkge30KICAgIH0KCiAgICBleHBvcnQgaW50ZXJmYWNlIFRyZWVWaXNpdG9yPFQsIFU+IHsKICAgICAgICB2aXNpdFByZWZpeChub2RlOiBOb2RlPFQ+IHwgbnVsbCk6IFU7CiAgICB9Cn0KCgpleHBvcnQgaW50ZXJmYWNlIEFkZGVyPFQsIFU+IHsKICAgIHplcm86IFU7CiAgICBhZGQoYXJnMDogVCwgYXJnMTogVCk6IFU7Cn0KCmNsYXNzIFByZWZpeEFkZGVyPFQ+IGltcGxlbWVudHMgVHJlZS5UcmVlVmlzaXRvcjxULCBUPiB7CiAgICBjb25zdHJ1Y3RvcigKICAgICAgICBwdWJsaWMgYWRkZXI6IEFkZGVyPFQsIFQ+CiAgICApIHt9CgogICAgdmlzaXRQcmVmaXgobm9kZTogVHJlZS5Ob2RlPFQ+IHwgbnVsbCk6IFQgewogICAgICAgIGlmIChub2RlID09IG51bGwpIHsKICAgICAgICAgICAgcmV0dXJuIHRoaXMuYWRkZXIuemVybzsKICAgICAgICB9IGVsc2UgewogICAgICAgICAgICByZXR1cm4gdGhpcy5hZGRlci5hZGQoCiAgICAgICAgICAgICAgICB0aGlzLmFkZGVyLmFkZChub2RlLnBheWxvYWQsIHRoaXMudmlzaXRQcmVmaXgobm9kZS5sZWZ0KSksCiAgICAgICAgICAgICAgICB0aGlzLnZpc2l0UHJlZml4KG5vZGUucmlnaHQpCiAgICAgICAgICAgICk7CiAgICAgICAgfQogICAgfQp9CgpjbGFzcyBJbnRlZ2VyQWRkZXIgaW1wbGVtZW50cyBBZGRlcjxpMzIsIGkzMj4gewogIHByaXZhdGUgX3plcm86IGkzMiA9IDA7CiAgZ2V0IHplcm8oKTogaTMyIHsKICAgIHJldHVybiB0aGlzLl96ZXJvOwogIH0KICBzZXQgemVybyh2YWw6IGkzMikgewogICAgdGhpcy5femVybyA9IHZhbDsKICB9CiAgYWRkKGFyZzA6IGkzMiwgYXJnMTogaTMyKTogaTMyIHsKICAgICAgcmV0dXJuIGFyZzAgKyBhcmcxOwogIH0KfQoKY2xhc3MgUHJlZml4SW50ZWdlckFkZGVyIGV4dGVuZHMgUHJlZml4QWRkZXI8aTMyPiB7fQoKY29uc3QgYWRkZXIgPSBuZXcgUHJlZml4SW50ZWdlckFkZGVyKG5ldyBJbnRlZ2VyQWRkZXIoKSk7CiMhaHRtbAo8dGV4dGFyZWEgaWQ9Im91dHB1dCIgc3R5bGU9ImhlaWdodDogMTAwJTsgd2lkdGg6IDEwMCUiIHJlYWRvbmx5PjwvdGV4dGFyZWE+CjxzY3JpcHQ+CmxvYWRlci5pbnN0YW50aWF0ZShtb2R1bGVfd2FzbSwgeyAvKiBpbXBvcnRzICovIH0pCiAgLnRoZW4oKHsgZXhwb3J0cyB9KSA9PiB7CiAgICBjb25zdCBvdXRwdXQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnb3V0cHV0JykKICAgIGZvciAobGV0IGkgPSAwOyBpIDw9IDEwOyArK2kpIHsKICAgICAgb3V0cHV0LnZhbHVlICs9IGBmaWIoJHtpfSkgPSAke2V4cG9ydHMuZmliKGkpfVxuYAogICAgfQogIH0pCjwvc2NyaXB0Pg==)

This pretty known issue.

cc @dcodeIO

**Comment by jriehl** [comment]
Okay, making the recommended changes definitely changes the result, but now that appears to hit #1675.  Thanks for the workaround, but IMO since this code works in Typescript, I would expect it to behave in Assemblyscript.
