### ISSUE TITLE
Some Checks not covered by the compiler

### ISSUE THREAD

**Issue by yjhmelody** [AssemblyScript/assemblyscript#1795]
```ts
class Bar {
    foo(): void {}
    constructor() {
        this.foo = 2;
    }
}
```
It returns:
```wasm
(module
 (memory $0 0)
 (table $0 1 funcref)
 (global $~lib/memory/__data_end i32 (i32.const 8))
 (global $~lib/memory/__stack_pointer (mut i32) (i32.const 16392))
 (global $~lib/memory/__heap_base i32 (i32.const 16392))
 (export "memory" (memory $0))
)
```

```ts
class Bar {
    foo(): void {}
    constructor() {
        this.foo = 2;
    }
}

let b = new Bar();
```

it failed:

```
Error [AssertionError]: assertion failed
    at i.assert (C:\Users\lenovo\AppData\Roaming\npm\node_modules\assemblyscript\dist\assemblyscript.js:7:735682)
    at f.compileAssignment (C:\Users\lenovo\AppData\Roaming\npm\node_modules\assemblyscript\dist\assemblyscript.js:7:273283)
    at f.compileBinaryExpression (C:\Users\lenovo\AppData\Roaming\npm\node_modules\assemblyscript\dist\assemblyscript.js:7:246636)
    at f.compileExpression (C:\Users\lenovo\AppData\Roaming\npm\node_modules\assemblyscript\dist\assemblyscript.js:7:237021)
    at f.compileExpressionStatement (C:\Users\lenovo\AppData\Roaming\npm\node_modules\assemblyscript\dist\assemblyscript.js:7:225884)
    at f.compileStatement (C:\Users\lenovo\AppData\Roaming\npm\node_modules\assemblyscript\dist\assemblyscript.js:7:222214)
    at f.compileStatements (C:\Users\lenovo\AppData\Roaming\npm\node_modules\assemblyscript\dist\assemblyscript.js:7:223242)
    at f.compileFunctionBody (C:\Users\lenovo\AppData\Roaming\npm\node_modules\assemblyscript\dist\assemblyscript.js:7:212450)
    at f.compileFunction (C:\Users\lenovo\AppData\Roaming\npm\node_modules\assemblyscript\dist\assemblyscript.js:7:211434)
    at f.ensureConstructor (C:\Users\lenovo\AppData\Roaming\npm\node_modules\assemblyscript\dist\assemblyscript.js:7:316039)
C:\Users\lenovo\AppData\Roaming\npm\node_modules\assemblyscript\node_modules\binaryen\index.js:54
Ha.push({iu:function(){La()}});function Ma(){var b=a.preRun.shift();Ga.unshift(b)}var Na=0,Oa=null,Pa=null;a.preloadedImages={};a.preloadedAudios={};function q(b){if(a.onAbort)a.onAbort(b);v(b);wa=!0;throw new va("abort("+b+"). Build with -s ASSERTIONS=1 for more info.");}function Qa(b){var d=Ra;return String.prototype.startsWith?b.startsWith(d):0===b.indexOf(d)}var Ra="data:application/octet-stream;base64,",Sa="<<< WASM_BINARY_FILE >>>";
```

**Comment by dcodeIO** [comment]
It is expected that the first snippet does not produce an error when the `class Bar` is not used anywhere in the code. It's only checked syntactically, but since it's not compiled, not fully checked semantically ([see](https://www.assemblyscript.org/basics.html#non-linear-compilation)).

The second one looks like a bug and should instead produce a diagnostic error.
