### ISSUE TITLE
Encounter strange compilation errors

### ISSUE THREAD

**Issue by yjhmelody** [AssemblyScript/assemblyscript#1817]
```
$ asc ./assembly/index.ts

▌ Whoops, the AssemblyScript compiler has crashed during initialize :-(
▌
▌ Here is a stack trace that may or may not be useful:
▌
▌ AssertionError: assertion failed
▌     at i.assert (C:\Users\lenovo\AppData\Roaming\npm\node_modules\assemblyscript\dist\assemblyscript.js:7:737048)
▌     at new v (C:\Users\lenovo\AppData\Roaming\npm\node_modules\assemblyscript\dist\assemblyscript.js:7:615872)
▌     at E.initialize (C:\Users\lenovo\AppData\Roaming\npm\node_modules\assemblyscript\dist\assemblyscript.js:7:591235)
▌     at Object.t.initializeProgram (C:\Users\lenovo\AppData\Roaming\npm\node_modules\assemblyscript\dist\assemblyscript.js:7:435219)
▌     at C:\Users\lenovo\AppData\Roaming\npm\node_modules\assemblyscript\cli\asc.js:817:22
▌     at measure (C:\Users\lenovo\AppData\Roaming\npm\node_modules\assemblyscript\cli\asc.js:1331:3)
▌     at Object.main (C:\Users\lenovo\AppData\Roaming\npm\node_modules\assemblyscript\cli\asc.js:815:27)
▌     at C:\Users\lenovo\AppData\Roaming\npm\node_modules\assemblyscript\bin\asc:19:47
▌
▌ If it refers to the dist files, try to 'npm install source-map-support' and
▌ run again, which should then show the actual code location in the sources.
▌
▌ If you see where the error is, feel free to send us a pull request. If not,
▌ please let us know: https://github.com/AssemblyScript/assemblyscript/issues
▌
▌ Thank you!

```

I meet error when do `asc ./assembly/index.ts`, but it's ok to do `asc ./index.ts`.

The content of `./index.ts` is
```ts
export * from "./assembly/index";
```

The project is https://github.com/patractlabs/as-scale-codec/tree/arrange-code.

**Comment by yjhmelody** [comment]
Most of the files under the assembly will encounter such errors
