### ISSUE TITLE
"SyntaxError: Unexpected token import" in transform

### ISSUE THREAD

**Issue by lrettig** [AssemblyScript/assemblyscript#182]
Hello,

As discussed in #178 I'm working on a transform script for ewasm (https://github.com/lrettig/ewasm-as/blob/master/transform.js). It works fine in dev mode, but when I try to run it in prod mode against the webpack-compiled module in `dist/`, I get the error:

```
ewasm-as/transform.js:2
import { NodeKind } from "assemblyscript/src/ast"
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:588:28)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at args.transform.forEach.transform (ewasm-as/node_modules/assemblyscript/cli/asc.js:214:9)
```

It looks like the webpack module doesn't like `import` and `export` statements. I tried switching to `require` statements but then I get an error that it can't find the module:

`Error: Cannot find module 'assemblyscript/src/ast'`

Any tips on how to import from AS inside a transform script? Thanks.

**Comment by lrettig** [comment]
I resolved this on my own. It was two issues:

- `node` (< v10) doesn't natively support `import` and `export` statements
- I cannot import TS in JS without using `ts-node`

I'm trying to do it this way now:

```javascript
require("ts-node").register({ project: path.join(__dirname, "tsconfig.json") })
require("assemblyscript/src/glue/js")
require("assemblyscript/src/glue/wasm/i64")
const NodeKind = require("assemblyscript/src/ast").NodeKind
```

I'm still stuck getting a bunch of compile errors like this:

```
TSError: ⨯ Unable to compile TypeScript:
../assemblyscript/src/glue/wasm/i64.ts(3,12): error TS2304: Cannot find name 'i64'.
../assemblyscript/src/glue/wasm/i64.ts(5,1): error TS1206: Decorators are not valid here.
../assemblyscript/src/glue/wasm/i64.ts(8,1): error TS1206: Decorators are not valid here.
../assemblyscript/src/glue/wasm/i64.ts(11,1): error TS1206: Decorators are not valid here.
../assemblyscript/src/glue/wasm/i64.ts(16,1): error TS1206: Decorators are not valid here.
../assemblyscript/src/glue/wasm/i64.ts(21,1): error TS1206: Decorators are not valid here.
../assemblyscript/src/glue/wasm/i64.ts(26,1): error TS1206: Decorators are not valid here.
../assemblyscript/src/glue/wasm/i64.ts(31,1): error TS1206: Decorators are not valid here.
../assemblyscript/src/glue/wasm/i64.ts(36,1): error TS1206: Decorators are not valid here.
../assemblyscript/src/glue/wasm/i64.ts(41,1): error TS1206: Decorators are not valid here.
../assemblyscript/src/glue/wasm/i64.ts(46,1): error TS1206: Decorators are not valid here.
../assemblyscript/src/glue/wasm/i64.ts(48,11): error TS2304: Cannot find name 'u64'.
```

**Comment by lrettig** [comment]
Rather than attempting to import the sources, I was able to make this work by exporting what I need from the main `assemblyscript.js` module (`NodeKind` for walking through the AST) and then importing it from that module. I'll keep playing with this to see if I can make it work without modifying the AS code.
