### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by DiriectorDoc** [AssemblyScript/assemblyscript#1854]
I can't seem to get assemblyscript to install properly. I have run the following commands:

    npm install --save @assemblyscript/loader
    npm install --save-dev assemblyscript

I have initialized the project

    npx asinit .

By problem arises when I try to build my `assembly/index.ts`

    npm run asbuild

I get this error:
<details>
<summary>Show error</summary>

```
Error: Error: Cannot find module 'typescript'
Require stack:
- C:\Users\OWNER\Documents\GitHub\WASM Test\node_modules\ts-node\dist\index.js
- C:\Users\OWNER\Documents\GitHub\WASM Test\node_modules\assemblyscript\index.js
- C:\Users\OWNER\Documents\GitHub\WASM Test\node_modules\assemblyscript\cli\asc.js
- C:\Users\OWNER\Documents\GitHub\WASM Test\node_modules\assemblyscript\bin\asc
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.register (C:\Users\OWNER\Documents\GitHub\WASM Test\node_modules\ts-node\src\index.ts:227:26)
    at loadAssemblyScriptJS (C:\Users\OWNER\Documents\GitHub\WASM Test\node_modules\assemblyscript\cli\asc.js:87:31)
    at loadAssemblyScript (C:\Users\OWNER\Documents\GitHub\WASM Test\node_modules\assemblyscript\cli\asc.js:148:22)
    at Object.<anonymous> (C:\Users\OWNER\Documents\GitHub\WASM Test\node_modules\assemblyscript\cli\asc.js:156:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
---
Error: Cannot find module './assemblyscript'
Require stack:
- C:\Users\OWNER\Documents\GitHub\WASM Test\node_modules\assemblyscript\cli\asc.js
- C:\Users\OWNER\Documents\GitHub\WASM Test\node_modules\assemblyscript\bin\asc
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at loadAssemblyScriptJS (C:\Users\OWNER\Documents\GitHub\WASM Test\node_modules\assemblyscript\cli\asc.js:96:21)
    at loadAssemblyScript (C:\Users\OWNER\Documents\GitHub\WASM Test\node_modules\assemblyscript\cli\asc.js:148:22)
    at Object.<anonymous> (C:\Users\OWNER\Documents\GitHub\WASM Test\node_modules\assemblyscript\cli\asc.js:156:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at loadAssemblyScriptJS (C:\Users\OWNER\Documents\GitHub\WASM Test\node_modules\assemblyscript\cli\asc.js:98:17)
    at loadAssemblyScript (C:\Users\OWNER\Documents\GitHub\WASM Test\node_modules\assemblyscript\cli\asc.js:148:22)
    at Object.<anonymous> (C:\Users\OWNER\Documents\GitHub\WASM Test\node_modules\assemblyscript\cli\asc.js:156:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at Object.<anonymous> (C:\Users\OWNER\Documents\GitHub\WASM Test\node_modules\assemblyscript\bin\asc:17:30)
```
</details>

My first thought was that typescript was not installed so I ran this:

    npm install -g typescript

...but I get the same error.

I also tried to use `asc` instead:

    asc assembly/index.ts -b test.wasm -O3

I get a different error:

<details>
<summary>Show error</summary>

    asc : The term 'asc' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is     
correct and try again.
</details>

This is very confusing and I can't find a solution.

**Comment by chipmunktail** [comment]
i got same error
