### ISSUE TITLE
SyntaxError: Unexpected token 'export' in Loader

### ISSUE THREAD

**Issue by CEbbinghaus** [AssemblyScript/assemblyscript#1858]
package.json:
```json
{
  "dependencies": {
    "@assemblyscript/loader": "^0.18.31"
  },
  "devDependencies": {
    "assemblyscript": "^0.18.31"
  }
}
```

Full Error:
```
/mnt/c/Users/CEbbi/Projects/WASMtest/node_modules/.pnpm/@assemblyscript/loader@0.18.31/node_modules/@assemblyscript/loader/index.js:318
export async function instantiate(source, imports = {}) {
^^^^^^

SyntaxError: Unexpected token 'export'
    at Module._compile (internal/modules/cjs/loader.js:881:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/mnt/c/Users/CEbbi/Projects/WASMtest/index.js:2:16)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
```

The error seems to be right here. Since it uses es-modules the node runtime is having problems with it as a js file. 
https://github.com/AssemblyScript/assemblyscript/blob/7e20ad2e53c31b3c26591e50de94ed859cda7f7e/lib/loader/index.js#L318

Is there something I missed or is this a problem with the library? I was just following the instructions under the [Quick Start](https://www.assemblyscript.org/quick-start.html)

**Comment by MaxGraey** [comment]
Just use umd variant `require("@assemblyscript/loader/umd")` or update node.js to latest version.

**Comment by CEbbinghaus** [comment]
> or update node.js to latest version.

Node Version is 14.17.0 LTS. does it require me to use Current?

**Comment by MaxGraey** [comment]
> Node Version is 14.17.0 LTS.

Hmm 14.17.0 should support ESM without flags. That's strange.

**Comment by CEbbinghaus** [comment]
figured out the issue, while my windows Node version was 14.17.0 my WSL one was 12.x so I had to update the WSL version and it fixed the problem. The error I was getting on windows was that it couldn't find the packages but I overlooked it.
