### ISSUE TITLE
Lambda expression without braces causes compiler error

### ISSUE THREAD

**Issue by Omega0x013** [AssemblyScript/assemblyscript#1905]
## Summary ##

When using a `=>` expression, I found that if there are no braces around the block, then a compiler error is thrown. The outputs are shown below, the latter output should be shown both times when there is no compilation error.

## Example ##

This small program causes a compiler error
```ts
let x: i32[] = [0,1,2,3,4,5];
x.forEach(y => Console.log(y));
```
until braces are added around `Console.log(y)`:
```ts
x.forEach(y => {Console.log(y)});
```

Output from first example:
```
▌ Whoops, the AssemblyScript compiler has crashed during compile :-(
▌ 
▌ Here is a stack trace that may or may not be useful:
▌ 
▌ AssertionError: assertion failed
▌     at assert (/home/xanderbielby/.local/share/node-v14.17.0-linux-x64/lib/node_modules/assemblyscript/dist/webpack:/assemblyscript/std/portable/index.js:199:9)
▌     at p.canOverflow (/home/xanderbielby/.local/share/node-v14.17.0-linux-x64/lib/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/flow.ts:1189:5)
▌     at f.compileFunctionBody (/home/xanderbielby/.local/share/node-v14.17.0-linux-x64/lib/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:1617:17)
▌     at f.compileFunction (/home/xanderbielby/.local/share/node-v14.17.0-linux-x64/lib/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:1535:17)
▌     at f.compileFunctionExpression (/home/xanderbielby/.local/share/node-v14.17.0-linux-x64/lib/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:7531:25)
▌     at f.compileExpression (/home/xanderbielby/.local/share/node-v14.17.0-linux-x64/lib/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:3467:21)
▌     at f.compileCallDirect (/home/xanderbielby/.local/share/node-v14.17.0-linux-x64/lib/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:6659:28)
▌     at f.compileCallExpression (/home/xanderbielby/.local/share/node-v14.17.0-linux-x64/lib/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:6278:21)
▌     at f.compileExpression (/home/xanderbielby/.local/share/node-v14.17.0-linux-x64/lib/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:3455:21)
▌     at f.compileExpressionStatement (/home/xanderbielby/.local/share/node-v14.17.0-linux-x64/lib/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:2492:17)
▌ 
▌ If it refers to the dist files, try to 'npm install source-map-support' and
▌ run again, which should then show the actual code location in the sources.
▌ 
▌ If you see where the error is, feel free to send us a pull request. If not,
▌ please let us know: https://github.com/AssemblyScript/assemblyscript/issues
▌ 
▌ Thank you!
```

Output from second example (expected output):
```
ERROR TS2304: Cannot find name 'Console'.

 x.forEach(y => {Console.log(y)});
                 ~~~~~~~
 in lambda.ts(3,17)

FAILURE 1 compile error(s)
```
I expect this error as I haven't imported anything

## Reproducing the problem ##

```
~ via  v14.17.0 
❯ cat lambda.ts 
let x: i32[] = [0,1,2,3,4,5];

x.forEach(y => Console.log(y));

~ via  v14.17.0 
❯ asc lambda.ts 

▌ Whoops, the AssemblyScript compiler has crashed during compile :-(
```

**Comment by ApsarasX** [comment]
I have this problem too.

**Comment by dcodeIO** [comment]
Looks like the problem comes from `x => someVoidFunction` not actually returning a value. I think it would be useful to account for this as a special case, even though it is technically illegal in AS since there is no `undefined` that could be returned.

**Comment by MaxGraey** [comment]
Btw for case when return type of closue expected `void` and `console.log` also return `void` such expression should be possible: `arr.forEach(x => Console.log(x));` while this `arr.forEach(x => x);` should print proper error
