### ISSUE TITLE
Compiler crash when we have two methods with same name in class

### ISSUE THREAD

**Issue by MaxGraey** [AssemblyScript/assemblyscript#191]
It will be great have better diagnostic error for this case:

```ts
class Foo {
   static a(): bool { return true; }
   static a(): bool { return false; }
}
```
Output:
```
ERROR: Compile error
    at Object.main (...../node_modules/assemblyscript/cli/asc.js:461:21)
    at Object.<anonymous> (...../node_modules/assemblyscript/bin/asc:3:60)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at findNodeScript.then.existing (...../.npm-packages/lib/node_modules/npm/node_modules/libnpx/index.js:268:14)
```

**Comment by dcodeIO** [comment]
Was this invalid?

**Comment by MaxGraey** [comment]
Yah. It printed error about duplicate identifier before `ERROR: Compile error`. I just miss this around warnings. May be if TS/AS errors already handled don't print stack trace and instead just print number of errors and warnings?
