### ISSUE TITLE
AS cannot dynamically call the interface method (generic method) in some situations

### ISSUE THREAD

**Issue by yjhmelody** [AssemblyScript/assemblyscript#1937]
I tried to write an encoder, but I found that AS cannot dynamically call the interface method (generic method), I always encounter `the AssemblyScript compiler has crashed during compile`, and I cannot reproduce a smaller example at present.

```
 Whoops, the AssemblyScript compiler has crashed during compile :-(
▌
▌ Here is a stack trace that may or may not be useful:
▌
▌ AssertionError: assertion failed
▌     at i.assert (D:\code\serde-as\node_modules\assemblyscript\dist\assemblyscript.js:7:753723)
▌     at h.resolveFunctionInclTypeArguments (D:\code\serde-as\node_modules\assemblyscript\dist\assemblyscript.js:7:686861)
▌     at h.maybeInferCall (D:\code\serde-as\node_modules\assemblyscript\dist\assemblyscript.js:7:659921)
▌     at f.compileCallExpression (D:\code\serde-as\node_modules\assemblyscript\dist\assemblyscript.js:7:296149)
▌     at f.compileExpression (D:\code\serde-as\node_modules\assemblyscript\dist\assemblyscript.js:7:253586)
▌     at f.compileExpressionStatement (D:\code\serde-as\node_modules\assemblyscript\dist\assemblyscript.js:7:242411)
▌     at f.compileStatement (D:\code\serde-as\node_modules\assemblyscript\dist\assemblyscript.js:7:238744)
▌     at f.compileStatements (D:\code\serde-as\node_modules\assemblyscript\dist\assemblyscript.js:7:239772)
▌     at f.compileFunctionBody (D:\code\serde-as\node_modules\assemblyscript\dist\assemblyscript.js:7:229034)
▌     at f.compileFunction (D:\code\serde-as\node_modules\assemblyscript\dist\assemblyscript.js:7:228050)
▌     at f.makeCallDirect (D:\code\serde-as\node_modules\assemblyscript\dist\assemblyscript.js:7:308518)
▌     at f.compileCallDirect (D:\code\serde-as\node_modules\assemblyscript\dist\assemblyscript.js:7:301785)
▌     at f.compileCallExpression (D:\code\serde-as\node_modules\assemblyscript\dist\assemblyscript.js:7:296367)
▌     at f.compileExpression (D:\code\serde-as\node_modules\assemblyscript\dist\assemblyscript.js:7:253586)
▌     at f.compileCallExpression (D:\code\serde-as\node_modules\assemblyscript\dist\assemblyscript.js:7:296300)
▌
▌ If it refers to the dist files, try to 'npm install source-map-support' and
▌ run again, which should then show the actual code location in the sources.
▌
▌ If you see where the error is, feel free to send us a pull request. If not,
▌ please let us know: https://github.com/AssemblyScript/assemblyscript/issues
▌
▌ Thank you!
```

This makes me unable to serialize an interface/abstract class, and because the AS enumeration does not support ADT, this makes it impossible to write more dynamic serialization functions (for example, a json value supports multiple kind of objects)

**Comment by willemneal** [comment]
The only way I've had success with this is to use an abstract class.  I plan to help improve interfaces, but for the time being I've avoid them.  Could you share your current code with interfaces?
