### ISSUE TITLE
Crashed if I import a lib by `transform` if the lib is not imported before

### ISSUE THREAD

**Issue by yjhmelody** [AssemblyScript/assemblyscript#1946]
It's better to print more friendly errors rather than being crashed.
```ts
Whoops, the AssemblyScript compiler has crashed during initialize :-(
▌ 
▌ Here is a stack trace that may or may not be useful:
▌ 
▌ AssertionError: assertion failed
▌     at assert (D:\work\patractlabs\ask-lite\node_modules\assemblyscript\dist\webpack:\assemblyscript\std\portable\index.js:199:9)
▌     at E.initialize (D:\work\patractlabs\ask-lite\node_modules\assemblyscript\dist\webpack:\assemblyscript\src\program.ts:1151:27)
▌     at Object.t.initializeProgram (D:\work\patractlabs\ask-lite\node_modules\assemblyscript\dist\webpack:\assemblyscript\src\index.ts:270:11)
▌     at D:\work\patractlabs\ask-lite\node_modules\assemblyscript\cli\asc.js:817:22
▌     at measure (D:\work\patractlabs\ask-lite\node_modules\assemblyscript\cli\asc.js:1331:3)
▌     at Object.main (D:\work\patractlabs\ask-lite\node_modules\assemblyscript\cli\asc.js:815:27)
▌     at D:\work\patractlabs\ask-lite\node_modules\assemblyscript\bin\asc:19:47
```

**Comment by dcodeIO** [comment]
Guessing: When adding an import `afterParse`, since the compiler doesn't parse that file anymore, it will not request it. To trigger requesting it, after adding the `import`, make sure to also add the respective entries in `Parser#backlog` and `Parser#dependees`.

**Comment by yjhmelody** [comment]
If a Source is modified by transform, I always delete the Source and replace the Source in the program and parser.
The strange thing is that it seems that this problem only occurs after I have used a newer version.
