### ISSUE TITLE
Why implementing a method without consistent type args  is legal?

### ISSUE THREAD

**Issue by yjhmelody** [AssemblyScript/assemblyscript#1962]
```ts
interface Foo {
    foo<T>(): void
}

class Bar implements Foo {
    foo(): void {}
}

let bar: Foo = new Bar; 
```

It works.

**Comment by MaxGraey** [comment]
It also [works in TS](https://www.typescriptlang.org/play?strict=true#code/JYOwLgpgTgZghgYwgAgGIHt3IN4FgBQyRyMmAPACoB8AFAJQBcyAbusACYEC+BBCANnADOQ5ACE4UZMAC2AB34QZEcKIxY8hYqXT0mrDjh75jQA)

**Comment by yjhmelody** [comment]
How about this?
```ts
interface Foo {
    foo<T>(t: T): void
}

class Bar implements Foo {
    foo(t: i32): void {

    }
}

class Baz implements Foo {
    foo(t: i8): void {
        
    }
}


let bar: Foo = new Bar; 
let baz: Foo = new Baz; 
bar.foo(1);
baz.foo(1);
```

```
Whoops, the AssemblyScript compiler has crashed during compile :-(
▌ 
▌ Here is a stack trace that may or may not be useful:
▌ 
▌ AssertionError: assertion failed
▌     at assert (D:\code\serde-as\node_modules\assemblyscript\dist\webpack:\assemblyscript\std\portable\index.js:199:9)
▌     at h.resolveFunction (D:\code\serde-as\node_modules\assemblyscript\dist\webpack:\assemblyscript\src\resolver.ts:2653:7)
▌     at finalizeVirtualStub (D:\code\serde-as\node_modules\assemblyscript\dist\webpack:\assemblyscript\src\compiler.ts:6988:46)
▌     at f.compile (D:\code\serde-as\node_modules\assemblyscript\dist\webpack:\assemblyscript\src\compiler.ts:550:14)
▌     at Object.t.compile (D:\code\serde-as\node_modules\assemblyscript\dist\webpack:\assemblyscript\src\index.ts:276:32)
▌     at D:\code\serde-as\node_modules\assemblyscript\cli\asc.js:833:31
▌     at measure (D:\code\serde-as\node_modules\assemblyscript\cli\asc.js:1331:3)
▌     at Object.main (D:\code\serde-as\node_modules\assemblyscript\cli\asc.js:831:24)
▌     at D:\code\serde-as\node_modules\assemblyscript\bin\asc:19:47
```

**Comment by MaxGraey** [comment]
Good point

**Comment by willemneal** [comment]
Shouldn't the type arg be inferred?

**Comment by JairusSW** [comment]
Yup. It should.

**Comment by yjhmelody** [comment]
But the interface could not support dynamic dispatch.
