### ISSUE TITLE
Unable to integrate the code of another transform package

### ISSUE THREAD

**Issue by yjhmelody** [AssemblyScript/assemblyscript#1975]
I need to reuse a transform for another transform. But I meet the following errors, it's about `redefine` problem.
```
FAIL  src/tests/debug.spec.ts
  ● Test suite failed to run

    TypeError: Cannot redefine property: signbit
        at Function.defineProperties (<anonymous>)

      at Object.call (../../node_modules/as-debug-transform/node_modules/assemblyscript/dist/webpack:/assemblyscript/std/portable/index.js:350:8)
      at i (../../node_modules/as-debug-transform/node_modules/assemblyscript/dist/webpack:/assemblyscript/webpack/bootstrap:19:32)
      at Object.call (../../node_modules/as-debug-transform/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/glue/js/index.ts:6:1)
      at __webpack_require__ (../../node_modules/as-debug-transform/node_modules/assemblyscript/dist/webpack:/assemblyscript/webpack/bootstrap:19:32)
      at ../../node_modules/as-debug-transform/node_modules/assemblyscript/dist/webpack:/assemblyscript/webpack/startup:3:1
      at factory (../../node_modules/as-debug-transform/node_modules/assemblyscript/dist/assemblyscript.js:7:758432)
      at ../../node_modules/as-debug-transform/node_modules/assemblyscript/dist/webpack:/assemblyscript/webpack/universalModuleDefinition:3:20
      at Object.<anonymous> (../../node_modules/as-debug-transform/node_modules/assemblyscript/dist/webpack:/assemblyscript/webpack/universalModuleDefinition:1:1)
```

**Comment by yjhmelody** [comment]
pin the issue for #1977

**Comment by dcodeIO** [comment]
Tackled in https://github.com/AssemblyScript/assemblyscript/pull/2049, now logging a warning on mismatch. Note that this fixes the redeclare problem, but not the underlying cause which comes from building against multiple potentially incompatible compiler versions. The proper fix remains to always depend on the same compiler installation everywhere.
