### ISSUE TITLE
inline const function causes negative local id

### ISSUE THREAD

**Issue by lrettig** [AssemblyScript/assemblyscript#198]
Minimal script to recreate:

```
export function add(): i32 {
  const a = function():i32 { return 1 }
  return a();
}

add();
```

I get this error:

```
[wasm-validator error in function $../assembly/main/add] unexpected false: get_local index must be small enough, on 
[i32] (get_local $4294967295)
[wasm-validator error in function $../assembly/main/add] unexpected false: get_local must have proper type, on 
[i32] (get_local $4294967295)
ERROR: Validate error
    at stats.validateTime.measure (/Users/lanerettig/wip/eth/assemblyscript/cli/asc.js:470:25)
    at measure (/Users/lanerettig/wip/eth/assemblyscript/cli/asc.js:809:3)
    at Object.main (/Users/lanerettig/wip/eth/assemblyscript/cli/asc.js:467:27)
    at Object.<anonymous> (/Users/lanerettig/wip/eth/assemblyscript/bin/asc:3:60)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
```

It looks like the culprit is [this line](https://github.com/AssemblyScript/assemblyscript/blob/671121bf702273c930d39999f02643d4f52b2e3d/src/compiler.ts#L2120), which creates a local with a negative ID.

**Comment by dcodeIO** [comment]
I see, yeah, a negative id used to be the indicator for an inlined local that has no actual index, but that has changed lately so the code you linked to needs to be updated.

**Comment by dcodeIO** [comment]
Should be fixed in the GC branch, expecting that one to land soon.
