### ISSUE TITLE
Type declarations fails unexpectedly

### ISSUE THREAD

**Issue by marcus-sa** [AssemblyScript/assemblyscript#202]
Tested in TS, works fine.

```js
export type VNodeChild = VNode | string | number;

export interface VNode {
	nodeName: string;
	attributes: VNodeAttributes;
	children: VNodeChild[];
	key?: string;
}

export interface VNodeAttributes {
	className?: string;
	onClick?: Function;
	key?: string;
}

export function h(nodeName: string | Function, attributes: VNodeAttributes = {}, ...children: VNodeChild[]): VNode {

	return typeof nodeName === 'function'
		? nodeName(attributes, ...children)
		: {
			key: attributes.key,
			nodeName,
			attributes,
			children,
		};
}
```

Error log

```sh
sc src/index.ts -t build/untouched.wat -b build/untouched.wasm --validate --sourceMap --measure

ERROR TS1005: 'null' expected.

 export type VNodeChild = VNode | string | number;
                                 ^
 in src/h.ts(1,32)

ERROR TS1110: Type expected.

        key?: string;
  ~~~
 in src/h.ts(7,1)

ERROR TS1003: Identifier expected.

        key?: string;
  ~~~
 in src/h.ts(7,1)

ERROR TS1109: Expression expected.

        key?: string;
     ~
 in src/h.ts(7,4)

ERROR TS1109: Expression expected.

 }
 ~
 in src/h.ts(8,0)

ERROR TS1110: Type expected.

        className?: string;
  ~~~~~~~~~
 in src/h.ts(11,1)

ERROR TS1003: Identifier expected.

        className?: string;
  ~~~~~~~~~
 in src/h.ts(11,1)

ERROR TS1109: Expression expected.

        className?: string;
           ~
 in src/h.ts(11,10)

ERROR TS1109: Expression expected.

        onClick?: Function;
          ~
 in src/h.ts(12,9)

ERROR TS1109: Expression expected.

        key?: string;
      ~
 in src/h.ts(13,5)

ERROR TS1109: Expression expected.

 }
 ~
 in src/h.ts(14,0)

ERROR TS1005: 'null' expected.

 export function h(nodeName: string | Function, attributes: VNodeAttributes = {}, ...children: VNodeChild[]): VNode {
                                     ^
 in src/h.ts(16,36)

ERROR TS1109: Expression expected.

 export function h(nodeName: string | Function, attributes: VNodeAttributes = {}, ...children: VNodeChild[]): VNode {
                                                          ~
 in src/h.ts(16,57)

ERROR TS1108: A 'return' statement can only be used within a function body.

        return typeof nodeName === 'function'
  ~~~~~~
 in src/h.ts(36,1)

ERROR TS1109: Expression expected.

 }
 ~
 in src/h.ts(44,0)

ERROR: Parse error
    at Object.main (C:\Users\esetm\Git\assemblyscript-starter\node_modules\assemblyscript\cli\asc.js:378:23)
    at Object.<anonymous> (C:\Users\esetm\Git\assemblyscript-starter\node_modules\assemblyscript\bin\asc:3:60)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:236:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:560:3)

```

**Comment by MaxGraey** [comment]
AssemblyScript is strongly typed subset of Typescript with AOT compilation which means dynamic features of TS not supported yet. Plz read [this limitations](https://github.com/AssemblyScript/assemblyscript/wiki/Limitations). Some of this limitation will relaxed when [Reference Types (anyref)](https://github.com/WebAssembly/reference-types/blob/master/proposals/reference-types/Overview.md) proposal landed.

**Comment by danbri** [comment]
Any news on this - the anyref page cited hasn't changed since 2020, i.e. https://github.com/WebAssembly/reference-types/blob/master/proposals/reference-types/Overview.md

**Comment by dcodeIO** [comment]
The reference types proposal has advanced to Phase 4 in the spec process meanwhile, that is it is now being standardized and should soon-ish become available for general use. Note, however, that the proposal alone has no impact on this issue, as it only defines basic reference types one can then use as a type annotation in AssemblyScript for external objects. This means that language-level classes remain unaffected for a bit longer. The proposal to look out for in this regard is [GC](https://github.com/WebAssembly/gc), but even GC will not introduce union types or `undefined` as per this issue.

For all the information, a more detailed [overview of the current status](https://www.assemblyscript.org/status.html) has meanwhile been added to the AS website as well.
