### ISSUE TITLE
AssemblyScript compiler has crashed during compile

### ISSUE THREAD

**Issue by onegitcat** [AssemblyScript/assemblyscript#2085]
```
▌ Whoops, the AssemblyScript compiler has crashed during compile :-(
▌ 
▌ Here is the stack trace hinting at the problem, perhaps it's useful?
▌ 
▌ AssertionError: assertion failed
▌     at assert (/code/aproject/node_modules/assemblyscript/dist/webpack:/assemblyscript/std/portable/index.js:200:11)
▌     at p.initThisFieldFlags (/code/aproject/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/flow.ts:587:5)
▌     at Function.createParent (/code/aproject/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/flow.ts:194:12)
▌     at new w (/code/aproject/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/program.ts:3632:22)
▌     at f.ensureConstructor (/code/aproject/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:8897:20)
▌     at f.compileObjectLiteral (/code/aproject/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:8778:21)
▌     at f.compileLiteralExpression (/code/aproject/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:8108:21)
▌     at f.compileExpression (/code/aproject/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:3514:21)
▌     at f.compileGlobal (/code/aproject/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:1259:25)
▌     at f.compileTopLevelStatement (/code/aproject/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:2137:20)
▌ 
▌ If it refers to the dist files, try to 'npm install source-map-support' and
▌ run again, which should then show the actual code location in the sources.
▌ 
▌ If you see where the error is, feel free to send us a pull request. If not,
▌ please let us know: https://github.com/AssemblyScript/assemblyscript/issues
▌ 
▌ Thank you!
```

**Comment by romdotdog** [comment]
Please provide code or a MCVE that leads to this crash
