### ISSUE TITLE
LHS of operator overload should check nullability

### ISSUE THREAD

**Issue by dcodeIO** [AssemblyScript/assemblyscript#2089]
In https://github.com/AssemblyScript/assemblyscript/issues/1891#issuecomment-930760909 it has been reported that operator overloads don't check nullability on the LHS:

```ts
let a // nullable
let b // non-nullable

a + b; // goes silently <-- here
b + a; // compile time error
```

**Comment by otaviopace** [comment]
As said in the comment, this only happens in **property access**. The example you gave here gives the compile time error correctly.

**Comment by dcodeIO** [comment]
Oh, what do you mean with property access? Something like the following?

```ts
let a.a // nullable
let a.c // non-nullable

a.a + a.c; // goes silently <-- here
a.c + a.a; // compile time error
```

**Comment by otaviopace** [comment]
Yes, like the example from the comment.

**Comment by otaviopace** [comment]
Hey @dcodeIO ! Thanks for working on this, it seems the compiler now is failing on this, but it's not giving an useful error message like if the nullable side is the RHS.

I just tried version [`0.19.18`](https://github.com/AssemblyScript/assemblyscript/releases/tag/v0.19.18) (where the fix got introduced) and [`0.19.22`](https://github.com/AssemblyScript/assemblyscript/releases/tag/v0.19.22) (latest), and both gave the "compiler has crashed" error message.

Example script:

```typescript
class Number {
  public constructor(
    public value: i32
  ) {}

  @operator('+')
  plus(other: Number): Number { // can be called with left hand side being nullable, should give compile time error
    return new Number(this.value + other.value);
  }
}

export function add(x: i32, y: i32): i32 {
  // Should give compile time error:
  let a: Number | null = null;
  let b = new Number(5);

  let c = a + b;

  return x + y + c.value;
}
```

Output:

```
╭─otaviopace at Otavios-MacBook-Pro in ⌁/as-overload-null-bug
╰─λ asc assembly/index.ts                                                                                                                                       nvim-4 | 0 (30.796s) < 21:08:43

▌ Whoops, the AssemblyScript compiler has crashed during compile :-(
▌
▌ Here is the stack trace hinting at the problem, perhaps it's useful?
▌
▌ AssertionError: assertion failed
▌     at assert (/Users/otaviopace/.nvm/versions/node/v17.3.1/lib/node_modules/assemblyscript/dist/webpack:/assemblyscript/std/portable/index.js:201:11)
▌     at f.compileBinaryOverload (/Users/otaviopace/.nvm/versions/node/v17.3.1/lib/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:5826:7)
▌     at f.compileBinaryExpression (/Users/otaviopace/.nvm/versions/node/v17.3.1/lib/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:4138:25)
▌     at f.compileExpression (/Users/otaviopace/.nvm/versions/node/v17.3.1/lib/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:3486:21)
▌     at f.compileVariableStatement (/Users/otaviopace/.nvm/versions/node/v17.3.1/lib/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:3077:25)
▌     at f.compileStatement (/Users/otaviopace/.nvm/versions/node/v17.3.1/lib/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:2245:21)
▌     at f.compileStatements (/Users/otaviopace/.nvm/versions/node/v17.3.1/lib/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:2293:23)
▌     at f.compileFunctionBody (/Users/otaviopace/.nvm/versions/node/v17.3.1/lib/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:1629:20)
▌     at f.compileFunction (/Users/otaviopace/.nvm/versions/node/v17.3.1/lib/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:1559:17)
▌     at f.compileElement (/Users/otaviopace/.nvm/versions/node/v17.3.1/lib/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:1018:38)
▌
▌ If it refers to the dist files, try to 'npm install source-map-support' and
▌ run again, which should then show the actual code location in the sources.
▌
▌ If you see where the error is, feel free to send us a pull request. If not,
▌ please let us know: https://github.com/AssemblyScript/assemblyscript/issues
▌
▌ Thank you!
```
![スクリーンショット 2022-01-12 21 13 27](https://user-images.githubusercontent.com/15306309/149243110-08cbdbdd-ebab-4ff0-b718-344e34e11a4c.png)

Example of inverting the nullable side to RHS (desired output):

```
╭─otaviopace at Otavios-MacBook-Pro in ⌁/as-overload-null-bug
╰─λ asc assembly/index.ts                                                                                                                                        fish-4 | 0 (8.211s) < 21:07:50
ERROR TS2322: Type 'assembly/index/Number | null' is not assignable to type 'assembly/index/Number'.

   let c = a + b;
               ~
 in assembly/index.ts(23,15)

FAILURE 1 compile error(s)
```

![スクリーンショット 2022-01-12 21 13 47](https://user-images.githubusercontent.com/15306309/149243206-366facc4-31ae-45d2-8365-1f6ff091ba81.png)
