### ISSUE TITLE
Compiler crash when using --transform json-as/transform

### ISSUE THREAD

**Issue by achille-roussel** [AssemblyScript/assemblyscript#2169]
I'm reporting a crash I encountered on a simple program which seems correct at first sight. Here's the setup I have to reproduce the issue:

```
$ asc --version
Version 0.19.20
```

* asconfig.json
```json
{
  "targets": {
    "debug": {
      "binaryFile": "build/untouched.wasm",
      "textFile": "build/untouched.wat",
      "sourceMap": true,
      "debug": true
    },
    "release": {
      "binaryFile": "build/optimized.wasm",
      "textFile": "build/optimized.wat",
      "sourceMap": true,
      "optimizeLevel": 3,
      "shrinkLevel": 0,
      "converge": false,
      "noAssert": false
    }
  },
  "options": {}
}
```

* package.json
```json
{
  "dependencies": {
    "json-as": "^0.2.6"
  },
  "devDependencies": {
    "assemblyscript": "^0.19.20"
  },
  "peerDependencies": {
    "visitor-as": "^0.6.0"
  }
}
```

* index.ts
```ts
import { JSON } from 'json-as'

@json
class JSONSchema {
    firstName: string
    lastName: string
    age: i32
}

export function parse(s: string): JSONSchema {
    return JSON.parse<JSONSchema>(s)
}
```

* test.ts
```ts
import { parse } from '.'

const parsed = parse(`{"firstName":"Jairus","lastName":"Tanaka","age":14}`)
```

This is the command I ran and the output I got (both debug and release modes produce the same crash):

```
$ asc test.ts --target release --transform json-as/transform

▌ Whoops, the AssemblyScript compiler has crashed during initialize :-(
▌
▌ Here is the stack trace hinting at the problem, perhaps it's useful?
▌
▌ AssertionError: assertion failed
▌     at assert (/private/tmp/json-as-test/node_modules/assemblyscript/dist/webpack:/assemblyscript/std/portable/index.js:201:11)
▌     at E.initialize (/private/tmp/json-as-test/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/program.ts:1153:27)
▌     at Object.t.initializeProgram (/private/tmp/json-as-test/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/index.ts:274:11)
▌     at /private/tmp/json-as-test/node_modules/assemblyscript/cli/asc.js:886:22
▌     at measure (/private/tmp/json-as-test/node_modules/assemblyscript/cli/asc.js:1409:3)
▌     at Object.main (/private/tmp/json-as-test/node_modules/assemblyscript/cli/asc.js:884:27)
▌     at /private/tmp/json-as-test/node_modules/assemblyscript/bin/asc:19:47
▌
▌ If it refers to the dist files, try to 'npm install source-map-support' and
▌ run again, which should then show the actual code location in the sources.
▌
▌ If you see where the error is, feel free to send us a pull request. If not,
▌ please let us know: https://github.com/AssemblyScript/assemblyscript/issues
▌
▌ Thank you!
```

**Comment by dcodeIO** [comment]
From a first look, the assertion happens at

https://github.com/AssemblyScript/assemblyscript/blob/81d5898ea99fac205be1706c8daabc36fe26a371/src/program.ts#L1152-L1153

which seems to indicate that the crash has something to do with the `import { parse } from '.'`.

**Comment by eflisback** [comment]
I'm having a similar issue with 
```json
{
    ....
    "assemblyscript": "^0.28.9",
    "json-as": "^1.1.23",
    ....
}
```

When running...
```
asc assembly/index.ts --target release --transform json-as/transform
```
...the compiler crashes if I'm using a `@json` annotation in `index.ts`.
```ts
import { JSON } from 'json-as'

@json
class Vec3 {
  x: f32 = 0.0;
  y: f32 = 0.0;
  z: f32 = 0.0;
}

export function add(a: i32, b: i32): i32 {
  return a + b;
}
```

I don't even need to attempt to parse anything. Just the annotation declaration seems to be what's leading the compiler to a crash.
