### ISSUE TITLE
[error] Error [ERR_REQUIRE_ESM]: Must use import to load ES Module

### ISSUE THREAD

**Issue by developersatish** [AssemblyScript/assemblyscript#2181]
I am getting this issue from yesterday from my build system

```
"@angular/animations": "^12.2.11",
"@angular/cdk": "^12.2.11",
"@angular/common": "^12.2.11",
"@angular/core": "^12.2.11",
```

`Node: 12.16.1`

```
[error] Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /mnt/buildramdisk/COBRA_GBCM_3_0_0_release/build/cobra-web-app-cae414f613c328a9293b37ad153b87aaad671b0a/node_modules/@assemblyscript/loader/index.js
require() of ES modules is not supported.
require() of /mnt/buildramdisk/COBRA_GBCM_3_0_0_release/build/cobra-web-app-cae414f613c328a9293b37ad153b87aaad671b0a/node_modules/@assemblyscript/loader/index.js from /mnt/buildramdisk/COBRA_GBCM_3_0_0_release/build/cobra-web-app-cae414f613c328a9293b37ad153b87aaad671b0a/node_modules/hdr-histogram-js/dist/wasm/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename /mnt/buildramdisk/COBRA_GBCM_3_0_0_release/build/cobra-web-app-cae414f613c328a9293b37ad153b87aaad671b0a/node_modules/@assemblyscript/loader/index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /mnt/buildramdisk/COBRA_GBCM_3_0_0_release/build/cobra-web-app-cae414f613c328a9293b37ad153b87aaad671b0a/node_modules/@assemblyscript/loader/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1174:13)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/mnt/buildramdisk/COBRA_GBCM_3_0_0_release/build/cobra-web-app-cae414f613c328a9293b37ad153b87aaad671b0a/node_modules/hdr-histogram-js/dist/wasm/index.js:20:18)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
```

**Comment by dcodeIO** [comment]
Looks a bit as if one dependency now uses ES modules instead of CommonJS, or added a new dependency that does so. Perhaps try asking at https://github.com/HdrHistogram/HdrHistogramJS, or Angular itself. Most likely not an issue with AssemblyScript.
