### ISSUE TITLE
Exporting interfaces results in build error

### ISSUE THREAD

**Issue by Dudeplayz** [AssemblyScript/assemblyscript#2185]
I've added the following export statement to index.ts: `export {AVRClockEventCallback, AVRInterruptConfig} from './interfaces';`
The `interfaces.ts` file looks like this:
```ts
export type CPUMemoryHook = (value: u8, oldValue: u8, addr: u16, mask: u8) => boolean;

export class CPUMemoryHooks extends Map<u32, CPUMemoryHook> {}

export type CPUMemoryReadHook = (addr: u16) => u8;

export class CPUMemoryReadHooks extends Map<u32, CPUMemoryReadHook> {}

export interface AVRInterruptConfig {
    ...
}

export type AVRClockEventCallback = () => void;
```

I am compiling with module generation enabled. I want to use the classes from outside of the module.

Here is the error message:
```log
▌ Whoops, the AssemblyScript compiler has crashed during buildTSD :-( 
▌ 
▌ Here is the stack trace hinting at the problem, perhaps it's useful?
▌ 
▌ AssertionError: assertion failed
▌     at assert (C:\Users\xxred\IdeaProjects\avr8js-research\node_modules\assemblyscript\dist\webpack:\assemblyscript\std\portable\index.js:201:11)
▌     at u.visitElement (C:\Users\xxred\IdeaProjects\avr8js-research\node_modules\assemblyscript\dist\webpack:\assemblyscript\src\definitions.ts:143:16)
▌     at u.visitFile (C:\Users\xxred\IdeaProjects\avr8js-research\node_modules\assemblyscript\dist\webpack:\assemblyscript\src\definitions.ts:80:14)
▌     at u.walk (C:\Users\xxred\IdeaProjects\avr8js-research\node_modules\assemblyscript\dist\webpack:\assemblyscript\src\definitions.ts:68:65)
▌     at u.build (C:\Users\xxred\IdeaProjects\avr8js-research\node_modules\assemblyscript\dist\webpack:\assemblyscript\src\definitions.ts:625:10)
▌     at Function.build (C:\Users\xxred\IdeaProjects\avr8js-research\node_modules\assemblyscript\dist\webpack:\assemblyscript\src\definitions.ts:376:36)
▌     at Object.t.buildTSD (C:\Users\xxred\IdeaProjects\avr8js-research\node_modules\assemblyscript\dist\webpack:\assemblyscript\src\index.ts:290:21)
▌     at C:\Users\xxred\IdeaProjects\avr8js-research\node_modules\assemblyscript\cli\asc.js:1173:34
▌     at measure (C:\Users\xxred\IdeaProjects\avr8js-research\node_modules\assemblyscript\cli\asc.js:1409:3)
▌     at Object.main (C:\Users\xxred\IdeaProjects\avr8js-research\node_modules\assemblyscript\cli\asc.js:1171:27)
▌ 
▌ If it refers to the dist files, try to 'npm install source-map-support' and
▌ run again, which should then show the actual code location in the sources.
▌ 
▌ If you see where the error is, feel free to send us a pull request. If not,
▌ please let us know: https://github.com/AssemblyScript/assemblyscript/issues
▌ 
▌ Thank you!

```

**Comment by Dudeplayz** [comment]
I have tested every single export and it fails on the interface export mentioned above. Is this unsupported? If yes, a concrete error message should be added. I also haven't found something in the documentation about it. Or have I overseen something?

**Comment by dcodeIO** [comment]
Testing with 0.20, the compiler appears not to crash anymore and instead produces the following warnings:

```
WARNING AS235: Only variables, functions and enums become WebAssembly module exports.

 export type AVRClockEventCallback = () => void;
             ~~~~~~~~~~~~~~~~~~~~~
 in assembly/interfaces.ts(12,13)

WARNING AS235: Only variables, functions and enums become WebAssembly module exports.

 export interface AVRInterruptConfig {
                  ~~~~~~~~~~~~~~~~~~
 in assembly/interfaces.ts(9,18)
```
