### ISSUE TITLE
Support casting externref to class

### ISSUE THREAD

**Issue by togekk1** [AssemblyScript/assemblyscript#2256]
For now, this example would work:
```
class HTMLElement {
  outerHTML: string;
}

export declare namespace document {
  @external("env", "document.getElementById")
  export function getElementById(id: string): HTMLElement;
}

export function main(): void {
  const app = document.getElementById("app")
  console.log(app.outerHTML);
}
```

This won't work:
```
class HTMLElement {
  appendChild: (ref: externref) => void;
}

export declare namespace document {
  @external("env", "document.getElementById")
  export function getElementById(id: string): HTMLElement;
}

export function main(div: externref): void {
  const app = document.getElementById("app");
  app.appendChild(div);
}
```

Output:
```
▌ Whoops, the AssemblyScript compiler has crashed during buildJS :-(
▌ 
▌ Here is the stack trace hinting at the problem, perhaps it's useful?
▌ 
▌ /media/togekk/Backup/code/www/as-regex-test/node_modules/assemblyscript/std/portable/index.js:200
▌     throw new AssertionError(message);
▌           ^
▌ 
▌ AssertionError: assertion failed
▌     at null.q.assert (/media/togekk/Backup/code/www/as-regex-test/node_modules/assemblyscript/std/portable/index.js:200:11)
▌     at Ar.makeLowerToValue (/media/togekk/Backup/code/www/as-regex-test/node_modules/assemblyscript/src/bindings/js.ts:1021:21)
▌     at Ar.makeLowerToMemory (/media/togekk/Backup/code/www/as-regex-test/node_modules/assemblyscript/src/bindings/js.ts:1188:10)
▌     at Ar.makeLowerRecord (/media/togekk/Backup/code/www/as-regex-test/node_modules/assemblyscript/src/bindings/js.ts:1259:14)
▌     at Ar.makeLowerToValue (/media/togekk/Backup/code/www/as-regex-test/node_modules/assemblyscript/src/bindings/js.ts:1072:39)
▌     at Ar.makeFunctionImport (/media/togekk/Backup/code/www/as-regex-test/node_modules/assemblyscript/src/bindings/js.ts:341:14)
▌     at Ar.build (/media/togekk/Backup/code/www/as-regex-test/node_modules/assemblyscript/src/bindings/js.ts:542:18)
▌     at Function.build (/media/togekk/Backup/code/www/as-regex-test/node_modules/assemblyscript/src/bindings/js.ts:99:40)
▌     at Module.$S (/media/togekk/Backup/code/www/as-regex-test/node_modules/assemblyscript/src/index-wasm.ts:335:20)
▌     at Module.Ue (/media/togekk/Backup/code/www/as-regex-test/node_modules/assemblyscript/cli/index.js:974:35)
▌ 
▌ If you see where the error is, feel free to send us a pull request. If not,
▌ please let us know: https://github.com/AssemblyScript/assemblyscript/issues
▌ 
▌ Thank you!
```
Is it possible to support import externref as a class?
Thanks!

**Comment by togekk1** [comment]
I found out that if I pass any function to JS as a function argument, the compiler will crash too. Don't know if it's relevant.

**Comment by dcodeIO** [comment]
There has been some discussion towards bindings to JS objects a while ago. A possible approach is to have separate `declare class`es that are not backed by `usize` but `externref`. Not available yet, but could look like

```ts
declare class HTMLElement {
  get outerHTML(): string;
}
```

where `outerHTML` would automatically become the respective binding. Probably still a way to go until then, including considering how GC types fit into the picture.
