### ISSUE TITLE
Passing the result of typeof into a generic fucntion causes an AssertionError in the compiler?

### ISSUE THREAD

**Issue by Heath123** [AssemblyScript/assemblyscript#2282]
Save this to `test.ts`
```typescript
function test<T>(value: T): void {}
test(typeof 1)
```

```
$ asc test.ts --binaryFile test.wasm

▌ Whoops, the AssemblyScript compiler has crashed during compile :-(
▌ 
▌ Here is the stack trace hinting at the problem, perhaps it's useful?
▌ 
▌ AssertionError: assertion failed
▌     at assert (/usr/lib/node_modules/assemblyscript/dist/webpack:/assemblyscript/std/portable/index.js:200:11)
▌     at h.resolveUnaryPrefixExpression (/usr/lib/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/resolver.ts:1781:16)
▌     at h.resolveExpression (/usr/lib/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/resolver.ts:1108:21)
▌     at h.maybeInferCall (/usr/lib/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/resolver.ts:746:27)
▌     at f.compileCallExpression (/usr/lib/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:6330:46)
▌     at f.compileExpression (/usr/lib/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:3490:21)
▌     at f.compileExpressionStatement (/usr/lib/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:2521:17)
▌     at f.compileStatement (/usr/lib/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:2213:21)
▌     at f.compileTopLevelStatement (/usr/lib/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:2175:25)
▌     at f.compileFile (/usr/lib/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:1111:12)
▌ 
▌ If it refers to the dist files, try to 'npm install source-map-support' and
▌ run again, which should then show the actual code location in the sources.
▌ 
▌ If you see where the error is, feel free to send us a pull request. If not,
▌ please let us know: https://github.com/AssemblyScript/assemblyscript/issues
▌ 
▌ Thank you!
```

**Comment by romdotdog** [comment]
This is a bug, for sure

for the record, the correct code is
```
function test<T>(value: T): void {}
test<typeof 1>(1)
```

**Comment by Heath123** [comment]
> This is a bug, for sure
> 
> for the record, the correct code is
> 
> ```ts
> function test<T>(value: T): void {}
> test<typeof 1>(1)
> ```

Well, not in this case, it was a log function and I wanted to see what the type was as a string

**Comment by dcodeIO** [comment]
There is an implementation of the `typeof` unary operator that is supposed to always return a string. It's relatively limited, in that the string adheres to what JS would return, but it should work.

https://github.com/AssemblyScript/assemblyscript/blob/e89cec29fd63eb43bed64af24163efd271c23554/src/compiler.ts#L9821-L9823

The assertion indicates that it is only implemented in `compile*` functions and that the resolver is missing it around [here](https://github.com/AssemblyScript/assemblyscript/blob/e89cec29fd63eb43bed64af24163efd271c23554/src/resolver.ts#L1702). That would in fact be a bug.
