### ISSUE TITLE
Exporting a function with a first-class function parameter crashes the compiler

### ISSUE THREAD

**Issue by romdotdog** [AssemblyScript/assemblyscript#2283]
## Code

```ts
export function foo(x: () => void): void {}
```

[Try it in the playground](https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1zcGVlZCZydW50aW1lPXN0dWIKZXhwb3J0IGZ1bmN0aW9uIGZvbyh4OiAoKSA9PiB2b2lkKTogdm9pZCB7fQojIWh0bWwKPHRleHRhcmVhIGlkPSJvdXRwdXQiIHN0eWxlPSJoZWlnaHQ6IDEwMCU7IHdpZHRoOiAxMDAlIiByZWFkb25seT48L3RleHRhcmVhPgo8c2NyaXB0IHR5cGU9Im1vZHVsZSI+CmNvbnN0IGV4cG9ydHMgPSBhd2FpdCBpbnN0YW50aWF0ZShhd2FpdCBjb21waWxlKCksIHsgLyogaW1wb3J0cyAqLyB9KQpjb25zdCBvdXRwdXQgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnb3V0cHV0JykKZm9yIChsZXQgaSA9IDA7IGkgPD0gMTA7ICsraSkgewogIG91dHB1dC52YWx1ZSArPSBgZmliKCR7aX0pID0gJHtleHBvcnRzLmZpYihpKX1cbmAKfQo8L3NjcmlwdD4=)

## Stack traces

```
▌ Whoops, the AssemblyScript compiler has crashed during buildTSD :-(
▌ 
▌ Here is the stack trace hinting at the problem, perhaps it's useful?
▌ 
▌ /data/assemblyscript/std/portable/index.js:200
▌     throw new AssertionError(message);
▌           ^
▌ 
▌ AssertionError: assertion failed
▌     at null.q.assert (/data/assemblyscript/std/portable/index.js:200:11)
▌     at TSDBuilder.toTypeScriptType (/data/assemblyscript/src/bindings/tsd.ts:239:21)
▌     at TSDBuilder.visitFunction (/data/assemblyscript/src/bindings/tsd.ts:156:20)
▌     at TSDBuilder.visitFunctionInstances (/data/assemblyscript/src/bindings/util.ts:132:53)
▌     at TSDBuilder.visitElement (/data/assemblyscript/src/bindings/util.ts:91:14)
▌     at TSDBuilder.visitFile (/data/assemblyscript/src/bindings/util.ts:59:14)
▌     at TSDBuilder.walk (/data/assemblyscript/src/bindings/util.ts:47:65)
▌     at TSDBuilder.build (/data/assemblyscript/src/bindings/tsd.ts:189:10)
▌     at Function.build (/data/assemblyscript/src/bindings/tsd.ts:37:41)
▌     at Module.JS (/data/assemblyscript/src/index-wasm.ts:330:21)
▌     at Object.Ue (/data/assemblyscript/cli/index.js:954:35)
▌     at async runTest (file:///data/assemblyscript/tests/compiler.js:194:23)
▌     at async file:///data/assemblyscript/tests/compiler.js:565:31
▌ 
▌ If you see where the error is, feel free to send us a pull request. If not,
▌ please let us know: https://github.com/AssemblyScript/assemblyscript/issues
▌ 
▌ Thank you!
```

```
▌ Whoops, the AssemblyScript compiler has crashed during buildJS :-(
▌ 
▌ Here is the stack trace hinting at the problem, perhaps it's useful?
▌ 
▌ /data/assemblyscript/std/portable/index.js:200
▌     throw new AssertionError(message);
▌           ^
▌ 
▌ AssertionError: assertion failed
▌     at null.q.assert (/data/assemblyscript/std/portable/index.js:200:11)
▌     at JSBuilder.makeLowerToValue (/data/assemblyscript/src/bindings/js.ts:1021:21)
▌     at JSBuilder.visitFunction (/data/assemblyscript/src/bindings/js.ts:390:16)
▌     at JSBuilder.visitFunctionInstances (/data/assemblyscript/src/bindings/util.ts:132:53)
▌     at JSBuilder.visitElement (/data/assemblyscript/src/bindings/util.ts:91:14)
▌     at JSBuilder.visitFile (/data/assemblyscript/src/bindings/util.ts:59:14)
▌     at JSBuilder.walk (/data/assemblyscript/src/bindings/util.ts:47:65)
▌     at JSBuilder.build (/data/assemblyscript/src/bindings/js.ts:616:10)
▌     at Function.build (/data/assemblyscript/src/bindings/js.ts:99:40)
▌     at Module.$S (/data/assemblyscript/src/index-wasm.ts:335:20)
▌     at Object.Ue (/data/assemblyscript/cli/index.js:956:35)
▌     at async runTest (file:///data/assemblyscript/tests/compiler.js:194:23)
▌     at async file:///data/assemblyscript/tests/compiler.js:565:31
▌ 
▌ If you see where the error is, feel free to send us a pull request. If not,
▌ please let us know: https://github.com/AssemblyScript/assemblyscript/issues
▌ 
▌ Thank you!
```

**Comment by tonibofarull0** [comment]
I'm interested in this topic too!
