### ISSUE TITLE
Reading from "node:fs/promises" is not handled by plugins (Unhandled scheme)

### ISSUE THREAD

**Issue by EightR0ad** [AssemblyScript/assemblyscript#2301]
getting an error when using webpack import build file(debug.js):
```
ERROR in node:fs/promises
Module build failed: UnhandledSchemeError: Reading from "node:fs/promises" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
    at E:\1工作\3测试\2022\assemblyscript研究\wasmWebpackTest\node_modules\webpack\lib\NormalModule.js:832:25
    at Hook.eval [as callAsync] (eval at create (E:\1工作\3测试\2022\assemblyscript研究\wasmWebpackTest\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (E:\1工作\3测试\2022\assemblyscript研究\wasmWebpackTest\node_modules\tapable\lib\Hook.js:18:14)
    at Object.processResource (E:\1工作\3测试\2022\assemblyscript研究\wasmWebpackTest\node_modules\webpack\lib\NormalModule.js:829:8)
    at processResource (E:\1工作\3测试\2022\assemblyscript研究\wasmWebpackTest\node_modules\loader-runner\lib\LoaderRunner.js:220:11)
    at iteratePitchingLoaders (E:\1工作\3测试\2022\assemblyscript研究\wasmWebpackTest\node_modules\loader-runner\lib\LoaderRunner.js:171:10)
    at runLoaders (E:\1工作\3测试\2022\assemblyscript研究\wasmWebpackTest\node_modules\loader-runner\lib\LoaderRunner.js:398:2)
    at NormalModule._doBuild (E:\1工作\3测试\2022\assemblyscript研究\wasmWebpackTest\node_modules\webpack\lib\NormalModule.js:819:3)
    at NormalModule.build (E:\1工作\3测试\2022\assemblyscript研究\wasmWebpackTest\node_modules\webpack\lib\NormalModule.js:963:15)
    at E:\1工作\3测试\2022\assemblyscript研究\wasmWebpackTest\node_modules\webpack\lib\Compilation.js:1371:12
```

import code:
```
import { multiply } from "./debug.js";
for (let i = 0; i < 10; i++) {
  const left = new Array(16);
  const right = new Array(16);
  for (let j = 0; j < 16; j++) {
    left[j] = Math.random();
    right[j] = Math.random();
  }

  const result = await multiply(left, right);
  console.debug(result);
}
```

next is webpack configuration:
```
const path = require("path");
const HtmlWebpackPlugin = require("html-webpack-plugin");

module.exports = {
  context: __dirname,
  entry: {
    app: "./src/index.js",
  },
  output: {
    filename: "app.js",
    path: path.resolve(__dirname, "dist"),
    sourcePrefix: "",
  },
  amd: {
    toUrlUndefined: true,
  },
  plugins: [
    new HtmlWebpackPlugin({
      template: "src/index.html",
    }),
  ],
  mode: "development",
  devtool: "eval",
  experiments: {
    topLevelAwait: true,
  },
};
```

**Comment by ericblade** [comment]
... how is this 'completed'?  how did this get resolved?  Having this issue right now.

**Comment by dcodeIO** [comment]
The `node:` scheme is a relatively recent addition. If I read correctly, it has meanwhile been backported to several earlier Node versions, but might still require updating Node.js.

**Comment by ericblade** [comment]
sure, using node 16, it seems to be a problem on the webpack side not on the node side.

**Comment by xgqfrms** [comment]
![image](https://user-images.githubusercontent.com/7291672/205114890-cf65dbe7-6f1c-4951-abda-b15f6562a8d5.png)


Projects deployed by `Vercel`  also have this problem. 

But it works fine in my local environment using `Node.js 18.x`.

**Comment by phidvss55** [comment]
Hi @xgqfrms 
Have you fixed this error? I'm facing this and have no idea how to fix this. 
- `node.js 18.x`
- `nextjs 13.x`   

The bug happened when I run `yarn run build` or deployed on **Vercel**

**Comment by amirgamil** [comment]
still facing this issue too

**Comment by xgqfrms** [comment]
@phidvss55 try it out.



<img width="1158" alt="image" src="https://github.com/AssemblyScript/assemblyscript/assets/7291672/b22df8f4-0b5c-4f44-8963-d61901b12104">

![image](https://github.com/AssemblyScript/assemblyscript/assets/7291672/cf19911c-394f-42c2-8ce7-b7e93f8ed7a7)

**Comment by robinmuhia** [comment]
Did any of you get a viable solution?

**Comment by QasimRRizvi** [comment]
Any solution for this?

**Comment by riccardolinares** [comment]
Same error!

**Comment by royvn** [comment]
Switching to node@18 worked for me.

**Comment by Ginowine** [comment]
I'm still having this issue, any solution yet?

**Comment by insanityfarm** [comment]
I am also having this problem! Not sure why the issue is closed.

**Comment by CountBleck** [comment]
Can't you set the `resolve.fallback["node:fs/promises"]` property to be `false`? (see [here](https://webpack.js.org/configuration/resolve/#resolvefallback))

**Comment by dcodeIO** [comment]
If this problem is so common, perhaps we should just remove the `node:` here?

https://github.com/AssemblyScript/assemblyscript/blob/de174c5f2863ea7947ba4496be4f9028c99d3367/src/bindings/js.ts#L980

**Comment by insanityfarm** [comment]
@CountBleck That doesn't work because of [this webpack bug](https://github.com/webpack/webpack/issues/14166). I also tried some of the workarounds discussed in that thread, like `externals['node:fs/promises'] = 'commonjs2 node:fs/promises'` and some variations on that theme, with no success.

**Comment by insanityfarm** [comment]
Okay, sorry for the spam — I found a solution that works with the bindings code as-is. I was close earlier... I needed to make the following additions to my webpack config:

```
{
    ...
    externals: {
        'node:fs/promises': 'commonjs2 node:fs/promises',
    },
    resolve: {
        fallback: {
            "fs": false
        }
    }
}
```

I had tried this earlier and was getting another error which I didn't realize was unrelated. (It was a runtime error caused by the browser trying to resolve that same import, which should be unreachable in that context... turns out it wasn't, because the `WebAssembly.compileStreaming()` call in the `try` block was failing, because my CSP didn't include `'unsafe-eval'`. Hope this information is helpful to others.

**Comment by CountBleck** [comment]
@Ginowine Does the above work for you?

**Comment by waleedshkt** [comment]
Looks like it's down to compatibility reasons between nodejs and nodejs-using packages versions. 

I recently bumped up nodejs to v22, and this error pops up. If I downgrade to v18, it goes away
