### ISSUE TITLE
Transform in `js` do not support package namespace in config

### ISSUE THREAD

**Issue by yjhmelody** [AssemblyScript/assemblyscript#2431]
asconfig.json: 
```json
 "options": {
        "transform": ["ask-transform", "as-serde-transform"],
        "importMemory": true,
        "initialMemory": 2,
        "maximumMemory": 16,
        "noExportMemory": true,
        "runtime": "stub",
        "use": "abort=",
        "disable": ["Sign-extension"]
    }
```
When I add a package namespace to the transform. It start panic:

```
 Whoops, the AssemblyScript compiler has crashed during initialize :-(
▌ 
▌ Here is the stack trace hinting at the problem, perhaps it's useful?
▌ 
▌ AssertionError: assertion failed
▌     at assert (/Users/yjhmelody/code/ask-lang/ask/node_modules/assemblyscript/dist/webpack:/assemblyscript/std/portable/index.js:200:11)
▌     at E.initialize (/Users/yjhmelody/code/ask-lang/ask/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/program.ts:1153:27)
▌     at Object.t.initializeProgram (/Users/yjhmelody/code/ask-lang/ask/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/index.ts:274:11)
▌     at /Users/yjhmelody/code/ask-lang/ask/node_modules/assemblyscript/cli/asc.js:886:22
▌     at measure (/Users/yjhmelody/code/ask-lang/ask/node_modules/assemblyscript/cli/asc.js:1409:3)
▌     at Object.main (/Users/yjhmelody/code/ask-lang/ask/node_modules/assemblyscript/cli/asc.js:884:27)
▌     at /Users/yjhmelody/code/ask-lang/ask/node_modules/assemblyscript/bin/asc:19:47
▌ 
▌ If it refers to the dist files, try to 'npm install source-map-support' and
▌ run again, which should then show the actual code location in the sources.
▌ 
▌ If you see where the error is, feel free to send us a pull request. If not,
▌ please let us know: https://github.com/AssemblyScript/assemblyscript/issues
▌ 
▌ Thank you!
```

**Comment by JesseCodeBones** [comment]
should is an issue for `ask-lang`?

**Comment by yjhmelody** [comment]
> should it an issue for `ask-lang`?

No, I think the namespace for transform caused this problem.
Because it works when I remove package namespace.
