### ISSUE TITLE
Latest commit cause compiler crashing

### ISSUE THREAD

**Issue by MaxGraey** [AssemblyScript/assemblyscript#25]
Latest [commit #ad92d91f014a7a7a8dfc2900c9fdccf11d47a43c][https://github.com/AssemblyScript/assemblyscript/commit/ad92d91f014a7a7a8dfc2900c9fdccf11d47a43c] cause to assertion error:

```
"AssertionError: assertion failed
    at n.assert (http://localhost:3000/assemblyscript.js:1:227147)
    at t.compile (http://localhost:3000/assemblyscript.js:1:77574)
    at Object.m [as compile] (http://localhost:3000/assemblyscript.js:1:266060)
    ...
```

**Comment by dcodeIO** [comment]
Hard to tell from that stack trace. Could you add the source map and trigger it again?

**Comment by MaxGraey** [comment]
It's little bit hard to do now. I think much easier run latest AS build in node.js

**Comment by dcodeIO** [comment]
Might also be that you are missing the [builtins library file](https://github.com/AssemblyScript/assemblyscript/blob/master/std/assembly/builtins.ts) now that these definitions are parsed instead of being added internally.

**Comment by MaxGraey** [comment]
Hmm, yes may be this cause to problem. But, if we build bundle (especially for browser) I think we should include all files

**Comment by dcodeIO** [comment]
Could well be that [this](https://github.com/AssemblyScript/assemblyscript/blob/master/src/compiler.ts#L231) is the assertion error you are seeing.

At this point, `assemblyscript.js` is more like a libassemblyscript, without any convenience features. Ideally, there'd also be a browser-build of `asc` with a virtual file system underneath that contains all the library components. You can also see [asc.js](https://github.com/AssemblyScript/assemblyscript/blob/master/bin/asc.js) for some insights on how library files are included in compilation.

**Comment by dcodeIO** [comment]
See: https://github.com/AssemblyScript/assemblyscript/blob/master/tests/bundled-asc.js
