### ISSUE TITLE
Compiler Crashes compiling SolanaWeb3

### ISSUE THREAD

**Issue by Brandon-T** [AssemblyScript/assemblyscript#2546]
Hi,
The compiler crashes when compiling `solanaWeb3`: https://github.com/solana-labs/solana-web3.js

```javascript
var EB="";function wA(){return{}}var DB=(()=>{var QQ=import.meta.url;return function(CA){CA=CA||{};var ng=typeof Object.defineProperties=="function"?Object.defineProperty:function(Q,C,I){return Q==Array.prototype||Q==Object.prototype||(Q[C]=I.value),Q};function tg(Q){Q=[typeof globalThis=="object"&&globalThis,Q,typeof window=="object"&&window,typeof self=="object"&&self,typeof global=="object"&&global];for(var C=0;C<Q.length;++C){var I=Q[C];if(I&&I.Math==Math)return I}throw Error("Cannot find global object")}var Wg=tg(this);function xg(Q,C){if(C)A:{var I=Wg;Q=Q.split(".");for(var g=0;g<Q.length-1;g++){var B=Q[g];if(!(B in I))break A;I=I[B]}Q=Q[Q.length-1],g=I[Q],C=C(g),C!=g&&C!=null&&ng(I,Q,{configurable:!0,writable:!0,value:C})}}xg("Array.prototype.includes",function(Q){return Q||function(C,I){var g=this;g instanceof String&&(g=String(g));var B=g.length;for(I=I||0,0>I&&(I=Math.max(I+B,0));I<B;I++){var E=g[I];if(E===C||Object.is(E,C))return!0}return!1}});var A;A||(A=typeof CA!="undefined"?CA:{});var gQ,FA;A.ready=new Promise(function(Q,C){gQ=Q,FA=C});var CQ=Object.assign({},A),dA="./this.program",eA=(Q,C)=>{throw C},BQ=typeof window=="object",BA=typeof importScripts=="function",j=typeof process=="object"&&typeof process.versions=="object"&&typeof process.versions.node=="string",e="",bA,YA,UA;if(j){e=BA?wA("path").dirname(e)+"/":EB+"/";var hA,lA;typeof wA=="function"&&(hA=wA("fs"),lA=wA("path")),bA=(Q,C)=>{var I=gA(Q);return I?C?I:I.toString():(Q=lA.normalize(Q),hA.readFileSync(Q,C?void 0:"utf8"))},UA=Q=>(Q=bA(Q,!0),Q.buffer||(Q=new Uint8Array(Q)),Q),YA=(Q,C,I)=>{var g=gA(Q);g&&C(g),Q=lA.normalize(Q),hA.readFile(Q,function(B,E){B?I(B):C(E.buffer)})},1<process.argv.length&&(dA=process.argv[1].replace(/\\/g,"/")),process.argv.slice(2),process.on("uncaughtException",function(Q){if(!(Q instanceof uA))throw Q}),process.on("unhandledRejection",function(Q){throw Q}),eA=(Q,C)=>{if(IQ)throw process.exitCode=Q,C;C instanceof uA||T("exiting due to exception: "+C),process.exit(Q)},A.inspect=function(){return"[Emscripten Module object]"}}else(BQ||BA)&&(BA?e=self.location.href:typeof document!="undefined"&&document.currentScript&&(e=document.currentScript.src),QQ&&(e=QQ),e.indexOf("blob:")!==0?e=e.substr(0,e.replace(/[?#].*/,"").lastIndexOf("/")+1):e="",bA=Q=>{try{var C=new XMLHttpRequest;return C.open("GET",Q,!1),C.send(null),C.responseText}catch(B){if(Q=gA(Q)){C=[];for(var I=0;I<Q.length;I++){var g=Q[I];255<g&&(zg&&x("Character code "+g+" ("+String.fromCharCode(g)+")  at offset "+I+" not in 0x00-0xFF."),g&=255),C.push(String.fromCharCode(g))}return C.join("")}throw B}},BA&&(UA=Q=>{try{var C=new XMLHttpRequest;return C.open("GET",Q,!1),C.responseType="arraybuffer",C.send(null),new Uint8Array(C.response)}catch(I){if(Q=gA(Q))return Q;throw I}}),YA=(Q,C,I)=>{var g=new XMLHttpRequest;g.open("GET",Q,!0),g.responseType="arraybuffer",g.onload=()=>{if(g.status==200||g.status==0&&g.response)C(g.response);else{var B=gA(Q);B?C(B.buffer):I()}},g.onerror=I,g.send(null)});var u=A.print||console.log.bind(console),T=A.printErr||console.warn.bind(console);Object.assign(A,CQ),CQ=null,A.thisProgram&&(dA=A.thisProgram),A.quit&&(eA=A.quit);var IA;A.wasmBinary&&(IA=A.wasmBinary);var IQ=A.noExitRuntime||!0;typeof WebAssembly!="object"&&x("no native wasm support detected");var VA,yA=!1,EQ=typeof TextDecoder!="undefined"?new TextDecoder("utf8"):void 0;function EA(Q,C){for(var I=C+NaN,g=C;Q[g]&&!(g>=I);)++g;if(16<g-C&&Q.buffer&&EQ)return EQ.decode(Q.subarray(C,g));for(I="";C<g;){var B=Q[C++];if(B&128){var E=Q[C++]&63;if((B&224)==192)I+=String.fromCharCode((B&31)<<6|E);else{var D=Q[C++]&63;B=(B&240)==224?(B&15)<<12|E<<6|D:(B&7)<<18|E<<12|D<<6|Q[C++]&63,65536>B?I+=String.fromCharCode(B):(B-=65536,I+=String.fromCharCode(55296|B>>10,56320|B&1023))}}else I+=String.fromCharCode(B)}return I}function R(Q){return Q?EA(l,Q):""}function DQ(Q,C,I,g){if(!(0<g))return 0;var B=I;g=I+g-1;for(var E=0;E<Q.length;++E){var D=Q.charCodeAt(E);if(55296<=D&&57343>=D){var o=Q.charCodeAt(++E);D=65536+((D&1023)<<10)|o&1023}if(127>=D){if(I>=g)break;C[I++]=D}else{if(2047>=D){if(I+1>=g)break;C[I++]=192|D>>6}else{if(65535>=D){if(I+2>=g)break;C[I++]=224|D>>12}else{if(I+3>=g)break;C[I++]=240|D>>18,C[I++]=128|D>>12&63}C[I++]=128|D>>6&63}C[I++]=128|D&63}}return C[I]=0,I-B}function kQ(Q){for(var C=0,I=0;I<Q.length;++I){var g=Q.charCodeAt(I);127>=g?C++:2047>=g?C+=2:55296<=g&&57343>=g?(C+=4,++I):C+=3}return C}var aA,t,l,oQ,S,H;function GQ(){var Q=VA.buffer;aA=Q,A.HEAP8=t=new Int8Array(Q),A.HEAP16=oQ=new Int16Array(Q),A.HEAP32=S=new Int32Array(Q),A.HEAPU8=l=new Uint8Array(Q),A.HEAPU16=new Uint16Array(Q),A.HEAPU32=H=new Uint32Array(Q),A.HEAPF32=new Float32Array(Q),A.HEAPF64=new Float64Array(Q)}var iQ,KQ=[],NQ=[],RQ=[],wQ=!1;function rg(){var Q=A.preRun.shift();KQ.unshift(Q)}var P=0,TA=null,DA=null;function x(Q){throw A.onAbort&&A.onAbort(Q),Q="Aborted("+Q+")",T(Q),yA=!0,Q=new WebAssembly.RuntimeError(Q+". Build with -sASSERTIONS for more info."),FA(Q),Q}var JA="data:application/octet-stream;base64,",r;

if(r="data:application/octet-stream;base64,"8AQZClCgsJ2IgCAPyIAgD9.................",


!r.startsWith(JA)){var FQ=r;r=A.locateFile?A.locateFile(FQ,e):e+FQ}function YQ(){var Q=r;try{if(Q==r&&IA)return new Uint8Array(IA);var C=gA(Q);if(C)return C;if(UA)return UA(Q);throw"both async and sync fetching of the wasm failed"}catch(I){x(I)}}function dg(){if(!IA&&(BQ||BA)){if(typeof fetch=="function"&&!r.startsWith("file://"))return fetch(r,{credentials:"same-origin"}).then(function(Q){if(!Q.ok)throw"failed to load wasm binary file at '"+r+"'";return Q.arrayBuffer()}).catch(function(){return YQ()});if(YA)return new Promise(function(Q,C){YA(r,function(I){Q(new Uint8Array(I))},C)})}return Promise.resolve().then(function(){return YQ()})}var $,fA;function uA(Q){this.name="ExitStatus",this.message="Program terminated with exit("+Q+")",this.status=Q}function XA(Q){for(;0<Q.length;)Q.shift()(A)}var sA=[],MA=0,X=0;function AA(Q){this.mB=Q,this.$A=Q-24,this.QB=function(C){H[this.$A+4>>2]=C},this.eB=function(){return H[this.$A+4>>2]},this.OB=function(C){H[this.$A+8>>2]=C},this.RB=function(){return H[this.$A+8>>2]},this.PB=function(){S[this.$A>>2]=0},this.vB=function(C){t[this.$A+12>>0]=C?1:0},this.KB=function(){return t[this.$A+12>>0]!=0},this.wB=function(C){t[this.$A+13>>0]=C?1:0},this.EB=function(){return t[this.$A+13>>0]!=0},this.NB=function(C,I){this.nB(0),this.QB(C),this.OB(I),this.PB(),this.vB(!1),this.wB(!1)},this.JB=function(){S[this.$A>>2]+=1},this.VB=function(){var C=S[this.$A>>2];return S[this.$A>>2]=C-1,C===1},this.nB=function(C){H[this.$A+16>>2]=C},this.IB=function(){return H[this.$A+16>>2]},this.LB=function(){if(XQ(this.eB()))return H[this.mB>>2];var C=this.IB();return C!==0?C:this.mB}}function UQ(Q){return f(new AA(Q).$A)}var cA=[];function c(Q){var C=cA[Q];return C||(Q>=cA.length&&(cA.length=Q+1),cA[Q]=C=iQ.get(Q)),C}var mA=(Q,C)=>{for(var I=0,g=Q.length-1;0<=g;g--){var B=Q[g];B==="."?Q.splice(g,1):B===".."?(Q.splice(g,1),I++):I&&(Q.splice(g,1),I--)}if(C)for(;I;I--)Q.unshift("..");return Q},kA=Q=>{var C=Q.charAt(0)==="/",I=Q.substr(-1)==="/";return(Q=mA(Q.split("/").filter(g=>!!g),!C).join("/"))||C||(Q="."),Q&&I&&(Q+="/"),(C?"/":"")+Q},eg=Q=>{var C=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(Q).slice(1);return Q=C[0],C=C[1],!Q&&!C?".":(C&&(C=C.substr(0,C.length-1)),Q+C)},hQ=Q=>{if(Q==="/")return"/";Q=kA(Q),Q=Q.replace(/\/$/,"");var C=Q.lastIndexOf("/");return C===-1?Q:Q.substr(C+1)};function bg(){if(typeof crypto=="object"&&typeof crypto.getRandomValues=="function"){var Q=new Uint8Array(1);return()=>(crypto.getRandomValues(Q),Q[0])}if(j)try{var C=wA("crypto");return()=>C.randomBytes(1)[0]}catch{}return()=>x("randomDevice")}function SA(){for(var Q="",C=!1,I=arguments.length-1;-1<=I&&!C;I--){if(C=0<=I?arguments[I]:"/",typeof C!="string")throw new TypeError("Arguments to path.resolve must be strings");if(!C)return"";Q=C+"/"+Q,C=C.charAt(0)==="/"}return Q=mA(Q.split("/").filter(g=>!!g),!C).join("/"),(C?"/":"")+Q||"."}function yQ(Q,C){var I=Array(kQ(Q)+1);return Q=DQ(Q,I,0,I.length),C&&(I.length=Q),I}var aQ=[];function JQ(Q,C){aQ[Q]={input:[],output:[],lB:C},OA(Q,lg)}var lg={open:function(Q){var C=aQ[Q.node.rdev];if(!C)throw new N(43);Q.tty=C,Q.seekable=!1},close:function(Q){Q.tty.lB.fsync(Q.tty)},fsync:function(Q){Q.tty.lB.fsync(Q.tty)},read:function(Q,C,I,g){if(!Q.tty||!Q.tty.lB.DB)throw new N(60);for(var B=0,E=0;E<g;E++){try{var D=Q.tty.lB.DB(Q.tty)}catch{throw new N(29)}if(D===void 0&&B===0)throw new N(6);if(D==null)break;B++,C[I+E]=D}return B&&(Q.node.timestamp=Date.now()),B},write:function(Q,C,I,g){if(!Q.tty||!Q.tty.lB.tB)throw new N(60);try{for(var B=0;B<g;B++)Q.tty.lB.tB(Q.tty,C[I+B])}catch{throw new N(29)}return g&&(Q.node.timestamp=Date.now()),B}},Vg={DB:function(Q){if(!Q.input.length){var C=null;if(j){var I=Buffer.alloc(256),g=0;try{g=hA.readSync(process.stdin.fd,I,0,256,-1)}catch(B){if(B.toString().includes("EOF"))g=0;else throw B}0<g?C=I.slice(0,g).toString("utf-8"):C=null}else typeof window!="undefined"&&typeof window.prompt=="function"?(C=window.prompt("Input: "),C!==null&&(C+=`

Error [AssertionError]: assertion failed
    at Y.assert (/Desktop/solana-web3.js/node_modules/assemblyscript/std/portable/index.js:198:11)
    at qn.parseExpression (/Desktop/solana-web3.js/node_modules/assemblyscript/src/parser.ts:4305:18)
    at qn.parseIfStatement (/Desktop/solana-web3.js/node_modules/assemblyscript/src/parser.ts:3265:28)
    at qn.parseStatement (/Desktop/solana-web3.js/node_modules/assemblyscript/src/parser.ts:2910:26)
    at qn.parseBlockStatement (/Desktop/solana-web3.js/node_modules/assemblyscript/src/parser.ts:2991:28)
    at qn.parseFunctionExpressionCommon (/Desktop/solana-web3.js/node_modules/assemblyscript/src/parser.ts:1632:21)
    at qn.parseExpressionStart (/Desktop/solana-web3.js/node_modules/assemblyscript/src/parser.ts:3942:23)
    at qn.parseExpression (/Desktop/solana-web3.js/node_modules/assemblyscript/src/parser.ts:4098:21)
    at qn.parseArguments (/Desktop/solana-web3.js/node_modules/assemblyscript/src/parser.ts:4075:23)
    at qn.maybeParseCallExpression (n/Desktop/solana-web3.js/node_modules/assemblyscript/src/parser.ts:4381:23)
```

**Comment by CountBleck** [comment]
AssemblyScript **doesn't compile JavaScript**. It compiles **a variant** of TypeScript. You'll have to use the actual TypeScript source files and most likely port them over to AssemblyScript.

**Comment by CountBleck** [comment]
Actually, I think I'm getting this wrong.

**Comment by CountBleck** [comment]
Actually, I think I'm getting this wrong.

**Comment by dcodeIO** [comment]
Looks like a normal TS project to me as well, which will likely not compile. Makes sense of course to make sure that the AS compiler won't crash when attempting and instead produce a useful error.
