### ISSUE TITLE
Include object and function type assemblyscript

### ISSUE THREAD

**Issue by aarthi0808** [AssemblyScript/assemblyscript#2680]
### Feature suggestion

Unable to use "Function" type in json object.

I have object like below

```
@json
class Player {
  firstName!: string;
  lastName!: funcref;
}

const player: Player = {
  firstName: "Emmet",
  lastName: function(){}
};
```
Here player.lastName should be of **Function** type

But it throws error 

```
Whoops, the AssemblyScript compiler has crashed during compile :-(
▌ 
▌ Here is the stack trace hinting at the problem, perhaps it's useful?
▌ 
▌ /usr/local/lib/node_modules/assemblyscript/std/portable/index.js:216
▌     throw new AssertionError(message);
▌           ^
▌ 
▌ AssertionError: assertion failed
▌     at null.Z.assert (/usr/local/lib/node_modules/assemblyscript/std/portable/index.js:216:11)
▌     at Hn.finishResolveClass (/usr/local/lib/node_modules/assemblyscript/src/resolver.ts:3433:19)
▌     at Hn.resolveClass (/usr/local/lib/node_modules/assemblyscript/src/resolver.ts:3222:10)
▌     at Hn.resolveClassInclTypeArguments (/usr/local/lib/node_modules/assemblyscript/src/resolver.ts:3652:17)
▌     at Hn.resolveNamedType (/usr/local/lib/node_modules/assemblyscript/src/resolver.ts:264:29)
▌     at Hn.resolveType (/usr/local/lib/node_modules/assemblyscript/src/resolver.ts:163:25)
▌     at $r.compileGlobal (/usr/local/lib/node_modules/assemblyscript/src/compiler.ts:1135:42)
▌     at $r.compileTopLevelStatement (/usr/local/lib/node_modules/assemblyscript/src/compiler.ts:2094:20)
▌     at $r.compileFile (/usr/local/lib/node_modules/assemblyscript/src/compiler.ts:1075:12)
▌     at $r.compile (/usr/local/lib/node_modules/assemblyscript/src/compiler.ts:524:14)
▌ 
▌ If you see where the error is, feel free to send us a pull request. If not,
▌ please let us know: https://github.com/AssemblyScript/assemblyscript/issues
```

**Comment by CountBleck** [comment]
`@json` isn't built-in to AssemblyScript, and functions can't be stringified to/parsed from JSON in any sane JSON serde library.
