### ISSUE TITLE
Runtime error trying to use process.hrtime()

### ISSUE THREAD

**Issue by brian-hay** [AssemblyScript/assemblyscript#2692]
### Question

When I try to use `process.hrtime()` I receive a runtime error:

```
import { process } from 'process';

export function start(): void {
  const time: u64 = process.hrtime();
}
```

```
caught TypeError: Illegal invocation
    at ~lib/process/process.hrtime (process.ts:36:15)
    at assembly/index/start (index.ts:63:21)
```

**Comment by dcodeIO** [comment]
Should be fixed by #2657. Mentions `performance.now`, which `process.hrtime` calls under the hood.
