### ISSUE TITLE
crash during compile

### ISSUE THREAD

**Issue by Pro2stinger** [AssemblyScript/assemblyscript#2707]
### Bug description

$ asc simple.ts -o simple.wasm

▌ Whoops, the AssemblyScript compiler has crashed during compile :-(
▌
▌ Here is the stack trace hinting at the problem, perhaps it's useful?
▌
▌ AssertionError: assertion failed
▌     at Y.assert (/data/data/com.termux/files/usr/lib/node_modules/assemblyscript/std/portable/index.js:216:11)
▌     at Kn.resolveFunctionType (/data/data/com.termux/files/usr/lib/node_modules/assemblyscript/src/resolver.ts:395:11)
▌     at Kn.resolveType (/data/data/com.termux/files/usr/lib/node_modules/assemblyscript/src/resolver.ts:172:25)
▌     at Kn.resolveFunction (/data/data/com.termux/files/usr/lib/node_modules/assemblyscript/src/resolver.ts:2866:32)
▌     at jr.compileModuleExport (/data/data/com.termux/files/usr/lib/node_modules/assemblyscript/src/compiler.ts:933:48)
▌     at jr.compileModuleExports (/data/data/com.termux/files/usr/lib/node_modules/assemblyscript/src/compiler.ts:914:14)
▌     at jr.compile (/data/data/com.termux/files/usr/lib/node_modules/assemblyscript/src/compiler.ts:549:14)
▌     at Module.z0 (/data/data/com.termux/files/usr/lib/node_modules/assemblyscript/src/index-wasm.ts:358:32)
▌     at Module.Me (/data/data/com.termux/files/usr/lib/node_modules/assemblyscript/cli/index.js:731:31)
▌     at async file:///data/data/com.termux/files/usr/lib/node_modules/assemblyscript/bin/asc.js:33:22
▌
▌ If you see where the error is, feel free to send us a pull request. If not,
▌ please let us know: https://github.com/AssemblyScript/assemblyscript/issues
▌
▌ Thank you!

### Steps to reproduce

`export function add(a: i32, b: i32): i32 {
  return a + b;
}

export function cache(func: (...args: any[]) => any): (...args: any[]) => any {
  return function cached(...args: any[]): any {
    return func(...args);
  }
}`

### AssemblyScript version

0.27.5

**Comment by MaxGraey** [comment]
AssemblyScript doesn't support `any` type. Also, doen't support spread syntax yet.
