### ISSUE TITLE
How to represent string - like a echo string function?

### ISSUE THREAD

**Issue by impvd** [AssemblyScript/assemblyscript#2710]
### Question

It seems that all the examples I can find is in `int` mode, such as:

```ts
export function add(a: i32, b: i32): i32 {
  return a + b + 100;
}
```

I did try to write a simple echo function as:

```ts
export function toUpperCase(input: string): string {
    return input
}
```

We could compile it:

```
❯ asc assembly/strs.ts --outFile build/out2.wasm --optimize
```

However, when I tried to import this function from cloudflare's side as:

```ts
import mod from '../build/out2.wasm';

const instance = await WebAssembly.instantiate(mod);

export default {
  async fetch() {    
	const retval = instance.toUpperCase("ok");
    return new Response(`Success: ${retval}`);
  },
};
```

But got error when triggering it by `wrangler dev`:

```
service core:user:assembly_worker1: Uncaught TypeError: WebAssembly.instantiate(): Imports argument must be present and must be an object
  at worker.js:25:34
```

Not sure this is the issue of CF or AssemblyScript, could anyone help to figure it out how to test a AssemblyScript Wasm file above using other runtime?

**Comment by CountBleck** [comment]
Use `--bindings raw`. Then, use the `instantiate` function exported by `../build/out2.js` instead of `WebAssembly.instantiate`. That'll let you pass strings between JS and Wasm.

**Comment by impvd** [comment]
@CountBleck Thanks for  your reply. I just change it to

```ts
import mod from '../build/out2.wasm';

// const instance = await WebAssembly.instantiate(mod);
const instance = await instantiate(mod)

export default {
  async fetch() {    
	const retval = instance.exports.toUpperCase("haha");
    return new Response(`Success: ${retval}`);
  },
};
```

And compile it with

```
❯ asc assembly/strs.ts --outFile build/out2.wasm --optimize --bindings raw
```

There's another error:

```
❯ wrangler dev
 ⛅️ wrangler 3.1.0
------------------
wrangler dev now uses local mode by default, powered by 🔥 Miniflare and 👷 workerd.
To run an edge preview session for your Worker, use wrangler dev --remote
⎔ Starting local server...
[mf:wrn] The latest compatibility date supported by the installed Cloudflare Workers Runtime is "2023-05-18",
but you've requested "2023-06-20". Falling back to "2023-05-18"...
service core:user:assembly_worker1: Uncaught ReferenceError: instantiate is not defined
  at worker.js:25:16
```

**Comment by CountBleck** [comment]
You forgot to import it 😛

Add `import {instantiate} from '../build/out2.wasm';` to the top of the file.

**Comment by impvd** [comment]
> You forgot to import it 😛
> 
> Add `import {instantiate} from '../build/out2.js';` to the top of the file.
> 
> Edit: I got the file extension wrong lol

After changing the code to

```ts
import mod from '../build/out2.wasm';
import {instantiate} from '../build/out2.js';

// const instance = await WebAssembly.instantiate(mod);
const instance = await instantiate(mod)

export default {
  async fetch() {    
	const retval = instance.exports.toUpperCase("haha");
    return new Response(`Success: ${retval}`);
  },
};
```

There's no error on starting `wrangler dev`

```
❯ wrangler dev
 ⛅️ wrangler 3.1.0
------------------
wrangler dev now uses local mode by default, powered by 🔥 Miniflare and 👷 workerd.
To run an edge preview session for your Worker, use wrangler dev --remote
⎔ Starting local server...
[mf:wrn] The latest compatibility date supported by the installed Cloudflare Workers Runtime is "2023-05-18",
but you've requested "2023-06-20". Falling back to "2023-05-18"...
[mf:inf] Ready on http://127.0.0.1:8787/
```

But when I browse http://127.0.0.1:8787/ , error occurred:

```
[mf:err] TypeError: Cannot read properties of undefined (reading 'toUpperCase')
```

**Comment by CountBleck** [comment]
Ah, replace `instance.exports with just `exports`, and replace `const instance =` with `const exports =`.

**Comment by CountBleck** [comment]
I'm glad it's all working for ypu. Have a good night :D

**Comment by impvd** [comment]
@CountBleck Yeah, you made my day!

But it seems that the real `toUpperCase` not work:

```
export function toUpperCase(input: string): string {
    let output = "";
    for (let i = 0; i < input.length; i++) {
      let charCode = input.charCodeAt(i);
      if (charCode >= 97 && charCode <= 122) { // Check if character is lowercase
        charCode -= 32; // Convert to uppercase by subtracting 32
      }
      output += String.fromCharCode(charCode);
    }
    return output;
}
```

Got error from wrangler:

```
⎔ Reloading local server...
service core:user:assembly_worker1: Uncaught Error: No such module "bbbd0a34bd157ae0eed454224749a86929dda9e8-out2.wasm".
  imported from "worker.js"
✘ [ERROR] MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
```

**Comment by CountBleck** [comment]
That Wrangler error about filenames is beyond me. Unless you yourself added that hash (the `blablabla` in `blablabla-out2.wasm`), I'm not sure where that came from. AS most certainly didn't generate it.
