### ISSUE TITLE
[question] compile TS code failed: ERROR TS1042: 'public' modifier cannot be used here.

### ISSUE THREAD

**Issue by mygithubsunny** [AssemblyScript/assemblyscript#304]
Hi, I used assemblyscript to compile [a ts example](https://github.com/EOSArgentina/eostypescript), and got follow errors:

```
$ cd ~/eostypescript/example
$ bash -x ./scripts/02-compile.sh 
+ asc ./src/gameoflife.ts -o ./gameoflife-ts/gameoflife-ts.wast --optimize --validate
ERROR TS1042: 'public' modifier cannot be used here.

   public static from_ds(ds : DataStream) : void {};
   ~~~~~~
 in ../src/eoslib.ts(24,2)

ERROR TS1042: 'static' modifier cannot be used here.

   public static from_ds(ds : DataStream) : void {};
          ~~~~~~
 in ../src/eoslib.ts(24,9)

ERROR TS1042: 'public' modifier cannot be used here.

   public static to_ds(instance :T, ds : DataStream) : void {};
   ~~~~~~
 in ../src/eoslib.ts(25,2)

ERROR TS1042: 'static' modifier cannot be used here.

   public static to_ds(instance :T, ds : DataStream) : void {};
          ~~~~~~
 in ../src/eoslib.ts(25,9)

ERROR: Parse error
    at Object.main (/Users/user/assemblyscript/cli/asc.js:389:23)
    at Object.<anonymous> (/Users/user/assemblyscript/bin/asc:3:60)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
+ cd ./gameoflife-ts/
+ sed -i.bak s/,/_/g gameoflife-ts.wast
+ rm gameoflife-ts.wast.bak
```

It looks like there is no grammar problem, and the source code of eoslib.ts likes this:
```
export interface ISerializable<T> {
  public static from_ds(ds : DataStream) : void {};
  public static to_ds(instance :T, ds : DataStream) : void {};
}
```

could anyone help explain it ? thanks a lot

**Comment by MaxGraey** [comment]
That's correct. In typescript interface's fields shouldn't contain any access modifiers like `static` or `public`

**Comment by mygithubsunny** [comment]
> That's correct. Typescript's interface fields shouldn't contain any access modifiers like `static` or `public`. But in the past this not handled by AssemblyScript.
> 
> Try change to this:
> 
> ```ts
> export interface ISerializable<T> {
>   from_ds(ds: DataStream): void;
>   to_ds(instance: T, ds: DataStream): void;
> }
> ```

thx a lot

**Comment by MaxGraey** [comment]
Closing. You are free to reopen it if there are more questions
