### ISSUE TITLE
TypeError: Cannot read property 'memory' of undefined

### ISSUE THREAD

**Issue by LinusU** [AssemblyScript/assemblyscript#322]
I have some code written in AssemblyScript that `throws`. There seems to be a problem in the `abort` function though, as it's trying to read `memory` of `this`, which is `undefined` 🤔 

```text
     TypeError: Cannot read property 'memory' of undefined
      at abort (node_modules/assemblyscript/lib/loader/index.js:29:44)
      at assembly/index/Bitmap#constructor (wasm-function[37]:167)
      at assembly/index/decodeTrueColorBmp (wasm-function[47]:51)
      at assembly/index/decodeBmp (wasm-function[48]:248)
      at Object.wrap [as decodeBmp] (node_modules/assemblyscript/lib/loader/index.js:199:12)
```

Here is the relevant part of the `abort` function:

```js
function abort(mesg, file, line, colm) {
    var memory = baseModule.memory || this.memory; // prefer exported, otherwise try imported
    /* ... */
  }
```

Apparently `this` seems to be `undefined` when being called from WebAssembly-land 🤔

**Comment by dcodeIO** [comment]
Seems `this` should actually be `imports.env` there
