### ISSUE TITLE
offsetof in generic function not supported. 

### ISSUE THREAD

**Issue by willemneal** [AssemblyScript/assemblyscript#394]
I'm trying to create a function that prints the contents of the object for debugging purposes.  I first thought I should use `sizeof<T>`, but realized that for objects it will return the size of it's pointer.  So the real solution is to use `offsetof<T>()`, which returns the end of the object.  While `sizeof<T>` worked, the following doesn't.

```ts
export declare function _log<T>(x: T, size: usize): void;
export declare function _log_str(x: string): void;


export function log<T>(item: T, isStr: boolean = false):void {
  if (isStr){
    _log_str(changetype<string>(item));
  }else{
    _log(item, offsetof<T>());
  }
}

export function log_str(item: string): void {
  log<string>(item, true);
}
```
Produces the following error:
```
ERROR AS100: Operation not supported.

     _log(item, offsetof<T>());
                ~~~~~~~~~~~~~
 in assembly/host/index.ts(10,15)

ERROR AS100: Operation not supported.

     _log(item, offsetof<T>());
                ~~~~~~~~~~~~~
 in assembly/host/index.ts(10,15)

ERROR AS100: Operation not supported.

     _log(item, offsetof<T>());
                ~~~~~~~~~~~~~
 in assembly/host/index.ts(10,15)

ERROR: Compile error
    at Object.main (/Users/willem/Research/wasm/assemblyscript/lib/parse/node_modules/assemblyscript/cli/asc.js:472:21)
    at Object.<anonymous> (/Users/willem/Research/wasm/assemblyscript/lib/parse/node_modules/assemblyscript/bin/asc:3:60)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
```

**Comment by MaxGraey** [comment]
```ts
export function log<T>(item: T): void {
  if (isReference<T>()) {
    if (isString<T>()) {
      _log_str(changetype<string>(item));
    } else {
     _log(item, offsetof<T>());
    }
  } else {
    _log(item, sizeof<T>());
  }
}
```

**Comment by MaxGraey** [comment]
But better do this like this:
https://webassembly.studio/?f=zkr0c51tjwb

**Comment by willemneal** [comment]
Thanks!  I forgot about those built ins.
