### ISSUE TITLE
Internal String Decorator error

### ISSUE THREAD

**Issue by jtenner** [AssemblyScript/assemblyscript#500]
![image](https://user-images.githubusercontent.com/3761339/53174876-c660d480-35b8-11e9-8fcd-ba284c8b88bf.png)

I would love to help with this one. Here's the text of the error. Looks like it's just a standard library error.  Am I missing something? Or may I just submit a pull request with the decorator removed?

```
ERROR TS1206: Decorators are not valid here.

 @inline export const enum CharCode {
 ~~~~~~~
 in ~lib/internal/string.ts(112,0)
```

**Comment by jtenner** [comment]
As it turns out, this particular error is because the assemblyscript compiler hasn't been properly built yet. I was instructed by @MaxGraey to use `npm link` and and `npm clean` out the compiler so it runs `ts-node`.

This resulted in a typescript error because it couldn't find the global `Promise` constructor type.

```
TSError: ⨯ Unable to compile TypeScript:
error TS2318: Cannot find global type 'Promise'.

    at createTSError (C:\Users\jtenner\Desktop\projects\assemblyscript\node_modules\ts-node\src\index.ts:253:12)
    at getOutput (C:\Users\jtenner\Desktop\projects\assemblyscript\node_modules\ts-node\src\index.ts:363:40)
    at Object.compile (C:\Users\jtenner\Desktop\projects\assemblyscript\node_modules\ts-node\src\index.ts:551:11)
    at Module.m._compile (C:\Users\jtenner\Desktop\projects\assemblyscript\node_modules\ts-node\src\index.ts:435:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\jtenner\Desktop\projects\assemblyscript\node_modules\ts-node\src\index.ts:438:12)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
npm ERR! Test failed.  See above for more details.
```

**Comment by jtenner** [comment]
Finally, after running `npm build` to try and avoid using ts node because of this type error, I found myself staring down the barrel of a non-descript error that looks like this:

```
[Log] using configuration C:\Users\jtenner\Desktop\projects\aspect\as-pect.config.js
including files assembly/__tests__/**/*.spec.ts
Compiling: assembly/__tests__/addedFiles.spec.ts 1 / 17
There was a compilation error when trying to create the wasm binary for file: assembly/__tests__/addedFiles.spec.ts.
{ AssertionError: assertion failed
    at t.assert (C:\Users\jtenner\Desktop\projects\assemblyscript\dist\assemblyscript.js:2:132929)
    at e.asNullable (C:\Users\jtenner\Desktop\projects\assemblyscript\dist\assemblyscript.js:1:115036)
    at t.resolveType (C:\Users\jtenner\Desktop\projects\assemblyscript\dist\assemblyscript.js:1:147113)
    at t.resolveFunction (C:\Users\jtenner\Desktop\projects\assemblyscript\dist\assemblyscript.js:1:161007)
    at t.resolveFunctionInclTypeArguments (C:\Users\jtenner\Desktop\projects\assemblyscript\dist\assemblyscript.js:1:162095)
    at t.resolveCallExpression (C:\Users\jtenner\Desktop\projects\assemblyscript\dist\assemblyscript.js:1:159399)
    at t.resolveExpression (C:\Users\jtenner\Desktop\projects\assemblyscript\dist\assemblyscript.js:1:155519)
    at t.resolvePropertyAccessExpression (C:\Users\jtenner\Desktop\projects\assemblyscript\dist\assemblyscript.js:1:150779)
    at t.resolveExpression (C:\Users\jtenner\Desktop\projects\assemblyscript\dist\assemblyscript.js:1:155363)
    at t.compileCallExpression (C:\Users\jtenner\Desktop\projects\assemblyscript\dist\assemblyscript.js:1:237916) message: 'assertion failed' }
```

**Comment by MaxGraey** [comment]
It seems some bad happened in resolver. 
cc @dcodeIO

**Comment by jtenner** [comment]
The file I'm trying to compile is a small one, so I'll run through what I think happened.

```ts
describe("added files", (): void => {
  it("should add added files when specified in the configuration using *.include.ts", (): void => {
    // @ts-ignore it's a tested global inside setup/Test.include.ts
    expect<i32>(meaningOfLife).toBe(42);
  });
});
```

It includes a file with a global so that things can be tested like this:

```ts
// @ts-ignore globals can be defined like this
@global
export const meaningOfLife: i32 = 42;
```

In any case, what I found was that it was trying to compile the expect function, and resolve the `T` type which is a value type, `i32`. Because the function type accepts `T | null`, it calls `asNullable` and fails an assertion involving type resolution. Please see the stack trace here:

```
    at t.assert (C:\Users\jtenner\Desktop\projects\assemblyscript\dist\assemblyscript.js:2:132929)
    at e.asNullable (C:\Users\jtenner\Desktop\projects\assemblyscript\dist\assemblyscript.js:1:115036)
    at t.resolveType (C:\Users\jtenner\Desktop\projects\assemblyscript\dist\assemblyscript.js:1:147113)
    at t.resolveFunction (C:\Users\jtenner\Desktop\projects\assemblyscript\dist\assemblyscript.js:1:161007)
```

Keep in mind this was *after* webpack was run to create the bundle. So in short, here are the things that need to be fixed:

1. Run webpack to get an updated bundle
2. Figure out why ts-node cannot find `Promise`
3. Figure out how to deal with nullable value types in the compiler when resolving them.

**Comment by dcodeIO** [comment]
I believe that the only way to trigger TS1206 there is using the old dist files with the new stdlib. I've updated dependencies and dist files now and things should work again, even with dist files. Please let me know if this helps.

**Comment by jtenner** [comment]
Yeah that sounds about right. I can try master again in a few hours to let you know how it goes.

**Comment by jtenner** [comment]
@dcodeIO the TS1206 error is fixed.  I still have problems with types not being nullable.

**Comment by sleagon** [comment]
The master branch seems to have been fixed now~~~ Nice work~


Here is a simple example: https://github.com/sleagon/hello-webassembly/tree/master/ts-wasm

**Comment by jtenner** [comment]
This issue is definitely fixed on master! Using the `isReference<T>()` compile time constant fixes everything I had a problem with.

Nullable types can now be discerned with `isNullable<T>()`. This only a compile time check to see if the type T has a `null` in it's type. This is not useful at runtime because all references can be null despite not being nullable. Instead I have switched to `isReference<T>()` to discern types that *can* be null, and perform null checks on those.

For instance:

```ts
class Expectation<T> {
  value: T;

  isNull(): void {
    // T is not nullable, but we should still check for null checks anyway
    if (isNullable<T>()) {
      // check for nulls here?
    }
  }
}
```
