### ISSUE TITLE
[Bug] Sourcemap generation error

### ISSUE THREAD

**Issue by jtenner** [AssemblyScript/assemblyscript#503]
I affixed my test suite to an old commit without the new resolver, so this may not be a bug, however when trying to generate a sourcemap from that commit I found an error.

```
Compiling: assembly/__tests__/beforeAndAfter.spec.ts 2 / 17
Fatal: Could not find pass: A

npm ERR! Test failed.  See above for more details.
```

I can remove this error by simply removing the `--sourceMap` flag from the compiler's arguments.

Another error I found when trying to disclude the test file that wasn't working, was this one.

```
RangeError: Invalid code point 172895010
    at Function.fromCodePoint (<anonymous>)
    at Function.String.fromCodePoints (C:\Users\jtenner\Desktop\projects\aspect\node_modules\assemblyscript\dist\assemblyscript.js:2:140412)
    at m (C:\Users\jtenner\Desktop\projects\aspect\node_modules\assemblyscript\dist\assemblyscript.js:1:40068)
    at e.toBinary (C:\Users\jtenner\Desktop\projects\aspect\node_modules\assemblyscript\dist\assemblyscript.js:1:31669)
    at stats.emitTime.measure (C:\Users\jtenner\Desktop\projects\aspect\node_modules\assemblyscript\cli\asc.js:570:23)
    at measure (C:\Users\jtenner\Desktop\projects\aspect\node_modules\assemblyscript\cli\asc.js:822:3)
    at Object.main (C:\Users\jtenner\Desktop\projects\aspect\node_modules\assemblyscript\cli\asc.js:569:25)
    at C:\Users\jtenner\Desktop\projects\aspect\lib\cli.js:184:31
    at Array.forEach (<anonymous>)
    at Object.asp (C:\Users\jtenner\Desktop\projects\aspect\lib\cli.js:176:30)
```

The files that generate the errors are located in the test suite on the aspect "sourcemaps" branch.

I can work on generating some smaller test cases to replicate the issue another time.

**Comment by MaxGraey** [comment]
`Invalid code point 172895010`. This same problem with sourcemaps. I got the same before resolver PR

**Comment by dcodeIO** [comment]
Can you try if this issue still persists with master?

**Comment by MaxGraey** [comment]
@dcodeIO It seems this issue is gone with latest master and updated binaryen. At least for WebAssembly Studio

**Comment by jtenner** [comment]
I'll be happy to report in a few hours. If you fixed it, thank you so much!

**Comment by jtenner** [comment]
It does look like this issue was resolved.

**Comment by MaxGraey** [comment]
@jtenner Could we close this?

**Comment by jtenner** [comment]
I just want to leave it open for a bit longer if that's okay! It looks really good.
