### ISSUE TITLE
Confusion between built-in functions and pointer to arrowed functions

### ISSUE THREAD

**Issue by helixd-2k18** [AssemblyScript/assemblyscript#517]
I found confusion situation. Built-in functions already is functions, but for use pointers to built-in functions, need arrow function (i.e. with `=> type`), but these functions isn't arrow (i.e. `: type`). 
SIMD released with this issue. 

```ts
// The entry file of your WebAssembly module.
import "allocator/buddy";

// struct interface with method pointers, should be arrow
class simetype<T,B> {
  add: (a: T, b: T) => T;
  extract_lane: (a: T, b: u8) =>  B;
  splat: (a: B) =>  T;
};

// use pointer to original functions (but SIMD isn't arrow)
let f32x4_t: simetype<v128,f32> = {
  add: f32x4.add,
  extract_lane: f32x4.extract_lane,
  splat: f32x4.splat
};

// imported function for logging
class simd_wrap<T,B> {
  constructor(protected a: T, protected M: simetype<T,B>){ };
  @inline public splat(a: B, c: simd_wrap<T,B>): simd_wrap<T,B> { return c.set(this.M.splat(a)); };
  @inline public get(): T { return this.a; };
  @inline public extract_lane(a: u8): B { return this.M.extract_lane(this.a, a); };
  @inline public set(a: T): simd_wrap<T,B> { this.a = a; return this; };
  @inline public add(b: simd_wrap<T,B>, c: simd_wrap<T,B>): simd_wrap<T,B> { return c.set(this.M.add(this.get(),b.get())); };
  @inline public ptr(): simd_wrap<T,B> { return this; };
};

function get_f32x4_opset(): simetype<v128,f32> {return f32x4_t;};

class f128_wrap extends simd_wrap<v128,f32>{};
export {f128_wrap, get_f32x4_opset};
```

```
C:\Data\Projects\AS-wizard>npm run asbuild

> wizard@1.0.0 asbuild C:\Data\Projects\AS-wizard
> npm run asbuild:untouched && npm run asbuild:optimized


> wizard@1.0.0 asbuild:untouched C:\Data\Projects\AS-wizard
> asc assembly/index.ts -b build/untouched.wasm -t build/untouched.wat --sourceMap --validate --debug    --enable mutable-global --enable simd

ERROR: AssertionError: assertion failed
    at t.assert (C:\Data\Projects\assemblyscript\dist\assemblyscript.js:2:132929)
    at t.resolveClass (C:\Data\Projects\assemblyscript\dist\assemblyscript.js:1:163803)
    at t.resolveClassInclTypeArguments (C:\Data\Projects\assemblyscript\dist\assemblyscript.js:1:165649)
    at t.resolveClass (C:\Data\Projects\assemblyscript\dist\assemblyscript.js:1:162529)
    at t.resolveClassInclTypeArguments (C:\Data\Projects\assemblyscript\dist\assemblyscript.js:1:165649)
    at t.compileClassUsingTypeArguments (C:\Data\Projects\assemblyscript\dist\assemblyscript.js:1:184883)
    at t.compileElement (C:\Data\Projects\assemblyscript\dist\assemblyscript.js:1:174775)
    at t.compileExports (C:\Data\Projects\assemblyscript\dist\assemblyscript.js:1:175578)
    at t.compile (C:\Data\Projects\assemblyscript\dist\assemblyscript.js:1:169298)
    at Object.t.compileProgram (C:\Data\Projects\assemblyscript\dist\assemblyscript.js:2:231538)
ERROR AS218: Cannot access method 'add' without calling it as it requires 'this' to be set.

   add: f32x4.add,
        ~~~~~~~~~
 in assembly/index.ts(13,7)

ERROR AS218: Cannot access method 'extract_lane' without calling it as it requires 'this' to be set.

   extract_lane: f32x4.extract_lane,
                 ~~~~~~~~~~~~~~~~~~
 in assembly/index.ts(14,16)

ERROR AS218: Cannot access method 'splat' without calling it as it requires 'this' to be set.

   splat: f32x4.splat
          ~~~~~~~~~~~
 in assembly/index.ts(15,9)

ERROR: Compile error
    at Object.main (C:\Data\Projects\assemblyscript\cli\asc.js:477:21)
    at Object.<anonymous> (C:\Data\Projects\assemblyscript\bin\asc:3:60)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:801:12)
    at internal/main/run_main_module.js:21:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wizard@1.0.0 asbuild:untouched: `asc assembly/index.ts -b build/untouched.wasm -t build/untouched.wat --sourceMap --validate --debug    --enable mutable-global --enable simd`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wizard@1.0.0 asbuild:untouched script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\helix\AppData\Roaming\npm-cache\_logs\2019-02-27T11_47_41_527Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wizard@1.0.0 asbuild: `npm run asbuild:untouched && npm run asbuild:optimized`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wizard@1.0.0 asbuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\helix\AppData\Roaming\npm-cache\_logs\2019-02-27T11_47_41_554Z-debug.log
```

**Comment by dcodeIO** [comment]
Yeah, these are really just instructions. One thing that could help is to use a generic context with the generic built-ins:

```ts
class Foo<T> {
  bar(a: v128, b: 128): v128 {
    return v128.add<T>(a, b);
  }
}
```

**Comment by helixd-2k18** [comment]
I described issue above of tracker, about generics.

**Comment by dcodeIO** [comment]
See your other issue, that should have been fixed with a commit already :)
