### ISSUE TITLE
Compile Error: changetype not supported

### ISSUE THREAD

**Issue by willemneal** [AssemblyScript/assemblyscript#549]
Any ideas?  This is from using the most recent AS version on github.
 
```ts
ERROR AS100: Operation not supported.

     return changetype<i8>(this.readVarint(size));
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 in assembly/buffer/index.ts(82,11)

ERROR: Compile error
    at Object.main (/Users/willem/Research/wasm/assemblyscript/lib/parse/node_modules/assemblyscript/cli/asc.js:477:21)
    at Object.<anonymous> (/Users/willem/Research/wasm/assemblyscript/lib/parse/node_modules/assemblyscript/bin/asc:4:60)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at findNodeScript.then.existing (/Users/willem/.nvm/versions/node/v11.7.0/lib/node_modules/npm/node_modules/libnpx/index.js:268:14)
```

**Comment by willemneal** [comment]
casting it, `<i8>this.readVarint(size)` worked.  Does this mean that change type is not needed anymore?

**Comment by dcodeIO** [comment]
Well, `changetype` is not a cast. It really just changes the type of something statically and does not result in any actual instructions. For example from one `usize` to another `usize` that is a reference and vice-versa.

**Comment by MaxGraey** [comment]
Yes, like cast `usize` to `Array<i32>` or `FooRef` to `FooBaseRef` and vise versa. And this unsafe. You should be careful with this.

**Comment by dcodeIO** [comment]
Whoops,

**Comment by willemneal** [comment]
Well it's used in the buffer of the parser and I'm pretty sure that I just copied it from the original.
