### ISSUE TITLE
Deducing type error when the method having generic parameter

### ISSUE THREAD

**Issue by LiaoPeng** [AssemblyScript/assemblyscript#551]
The [source code](https://webassembly.studio/?f=9yd4gavty7a).

```typescript
import "allocator/arena";
import { Action , getMethod, Method, Action1, getMethod1 } from "./name";

declare function sayHello(): void;

sayHello();

export function add(x: i32, y: i32): i32 {
  return x + y;
}

var mth: Method = getMethod("name");
Action.attach(mth, "");


var mth1 = getMethod1("name");
Action1.attachWithoutData(mth1);
Action1.attach(mth1, "");
```

The compiled result:
```
ERROR TS2304: Cannot find name 'Method1'.

   static attach<T>(mth: Method1, data: T):void  {
                         ~~~~~~~
 in name.ts(29,24)


ERROR: Compile error
    at exports.main (https://assemblyscript.github.io/assemblyscript/dist/asc.js:1:457291)
    at Object.eval [as main] (eval at d (https://webassembly.studio/dist/main.bundle.js:1:32473), <anonymous>:20:12)
    at r.eval [as promiseMaker] (eval at gulp (https://webassembly.studio/dist/main.bundle.js:1:34093), <anonymous>:7:7)
    at o.makePromise (https://webassembly.studio/dist/main.bundle.js:1:31658)
    at s.runInstance (https://webassembly.studio/dist/main.bundle.js:1:31954)

[info]: Task build is completed
Saving Project ...
Saved Project OK
```

The below code compiled successful.
```
var mth: Method = getMethod("name");
Action.attach(mth, "");
```

I expected the below code also compiled successful.

```
var mth1 = getMethod1("name");
Action1.attach(mth1, "");

```

**Comment by MaxGraey** [comment]
```ts
export class Method {
  name: string;
}
```

```ts
export class Method1 {
  name: string;
}
```

So actually this two different classes. So you expect structural typing which is not support yet

**Comment by dcodeIO** [comment]
This actually looks like a resolver error.

```ts
// name.ts

export class Method1 {
}

export function getMethod1(name: string): Method1 {
  return changetype<Method1>(0);
}

export class Action1 {
  static attach<T>(mth: Method1, data: T): void  {
  }
}
```

This doesn't work:

```ts
import { Action1, getMethod1 } from "./name";

var mth1 = getMethod1("name");
Action1.attach(mth1, "");
```

but this does:

```ts
import { Action1, Method1, getMethod1 } from "./name";
//                              ^ !
var mth1 = getMethod1("name");
Action1.attach(mth1, "");
```

**Comment by dcodeIO** [comment]
Closing this issue as part of [2020 vacuum](https://github.com/AssemblyScript/assemblyscript/issues/1277) because it appears to have been solved meanwhile. The latest failing example did work in a quick test. If there are any remaining issues, feel free to open a new issue or re-open this one.
