### ISSUE TITLE
How to create TypedArray from an ArrayBuffer?

### ISSUE THREAD

**Issue by hjlld** [AssemblyScript/assemblyscript#581]
Hi, i'm new to assemblyscript. i'm trying to export OpenCTM(witch is an 3D geometry compression format) to wasm using assemlbyscript.

The original code create an entire  ArrayBuffer and slice it to different sections, and for each section create a TypedArray, then write or read them, bla, bla, bla.

``` javascript

// JS

...

this.data = new ArrayBuffer((i + v + n + (u * header.uvMapCount) + (a * header.attrMapCount)) * 4);

this.indices = new Uint32Array(this.data, 0, i);

this.vertices = new Float32Array(this.data, i * 4, v);

...

```

but assemblyscript only support create typedarray with a `length` argument, but not from an ArrayBuffer.

so is there some other way to make it?

or is there an polyfill for `new TypedArray(buffer [, byteOffset [, length]]);`?

**Comment by MaxGraey** [comment]
Currently function/constructor overloading not existing. So only `TypedArray(len)` supported. But you could create your own helper function for workaround this limitation:
```ts
import "allocator/arena";

export function createTypedArray<TArray>(
  buffer: ArrayBuffer, 
  byteOffset: usize = 0, 
  byteLength: usize = 0
): TArray {
  var arr = memory.allocate(offsetof<TArray>());
  store<usize>(arr, buffer, offsetof<TArray>("buffer"));
  store<i32>(arr, byteOffset, offsetof<TArray>("byteOffset"));
  store<i32>(arr, byteLength, offsetof<TArray>("byteLength"));
  return changetype<TArray>(arr);
}

// Usage tests:
var buf = new ArrayBuffer(4 * 10);
var arr = createTypedArray<Uint32Array>(buf, 4, 9);
assert(arr.buffer == buf);
assert(arr.byteOffset == 4);
assert(arr.byteLength == 9);
```

**Comment by hjlld** [comment]
@MaxGraey Thank you very much!

but after adding this function, the asc compiler throw a exact same error as #518 , then as mentioned in that issue, i git clone the repo, run `npm link` and `npm run build`, then compile again, but the error still exist.

**Comment by hjlld** [comment]
@MaxGraey Thank you very much, but this function always create a typedarray with 1/4 length.

see this wasm studio instance:  https://webassembly.studio/?f=w4o9m7qrp2

for example:
``` javascript
let array1= createTypedArray(buf, 0, 12)
array1.lenth      // 3

let array1= createTypedArray(buf, 0, 36)
array1.lenth       // 9

let array1= createTypedArray(buf, 0, 11)
array1.lenth       // 2
```

**Comment by MaxGraey** [comment]
```createTypedArray<Float64Array>(buf, 0, 32)```
output: 4 because `32 / sizeof<f64> = 4`
```createTypedArray<Int32Array>(buf, 0, 32)```
output: 8 because `32 / sizeof<i32> = 8`

because last argument is `byteLength` if you want `length` you should modify code:
```ts
export function createTypedArray<TArray, T>(
  buffer: ArrayBuffer, 
  byteOffset: usize = 0, 
  length: usize = 0
): TArray {
  var arr = memory.allocate(offsetof<TArray>());
  var byteLength = length << alignof<T>();
  store<ArrayBuffer>(arr, buffer, offsetof<TArray>("buffer"));
  store<i32>(arr, byteOffset, offsetof<TArray>("byteOffset"));
  store<i32>(arr, byteLength, offsetof<TArray>("byteLength"));
  return changetype<TArray>(arr);
}
```
and use as:
```ts
let indices = createTypedArray<Int32Array, i32>(buf, 0, 8);
return indices.length;
```
https://webassembly.studio/?f=lyq7jbk64lj

**Comment by hjlld** [comment]
You're very appreciated!  With you help I have exported OpenCTM to WASM.

Next I'll explore how to share non-copy array buffer to WebGL.

AssemblyScript is really the best and easiest way to get started in WASM for frontend programmers.

**Comment by FranklinWaller** [comment]
I believe this is not compatible with the latest version of AssemblyScript. Compiling the code: 
```
export function createTypedArray<TArray>(
    buffer: ArrayBuffer, 
    byteOffset: usize = 0, 
    byteLength: usize = 0
  ): TArray {
    var arr = __alloc(offsetof<TArray>(), idof<TArray>());
    store<ArrayBuffer>(arr, buffer, offsetof<TArray>("buffer"));
    store<i32>(arr, byteOffset, offsetof<TArray>("byteOffset"));
    store<i32>(arr, byteLength, offsetof<TArray>("byteLength"));
    return changetype<TArray>(arr);
}
 ```

And using it: ```createTypedArray<Uint32Array>(hash, 4, 9);``` Resulted in the below error:

```

ERROR TS2460: Type '~lib/typedarray/Uint32Array' has no property 'buffer'.

     store<ArrayBuffer>(arr, buffer, offsetof<TArray>("buffer"));
                                                      ~~~~~~~~
 in contracts/rutile/utils/createTypedArray.ts(32,53)

ERROR AS220: Expression must be a compile-time constant.

     store<ArrayBuffer>(arr, buffer, offsetof<TArray>("buffer"));
                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~
 in contracts/rutile/utils/createTypedArray.ts(32,36)

ERROR TS2460: Type '~lib/typedarray/Uint32Array' has no property 'byteOffset'.

     store<i32>(arr, byteOffset, offsetof<TArray>("byteOffset"));
                                                  ~~~~~~~~~~~~
 in contracts/rutile/utils/createTypedArray.ts(33,49)

ERROR AS220: Expression must be a compile-time constant.

     store<i32>(arr, byteOffset, offsetof<TArray>("byteOffset"));
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 in contracts/rutile/utils/createTypedArray.ts(33,32)

ERROR TS2460: Type '~lib/typedarray/Uint32Array' has no property 'byteLength'.

     store<i32>(arr, byteLength, offsetof<TArray>("byteLength"));
                                                  ~~~~~~~~~~~~
 in contracts/rutile/utils/createTypedArray.ts(34,49)

ERROR AS220: Expression must be a compile-time constant.

     store<i32>(arr, byteLength, offsetof<TArray>("byteLength"));
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 in contracts/rutile/utils/createTypedArray.ts(34,32)

ERROR: Compile error
    at Object.main (/Volumes/Mac Space/Workspace/Rutile/InternalContracts/node_modules/assemblyscript/cli/asc.js:492:21)
    at Object.<anonymous> (/Volumes/Mac Space/Workspace/Rutile/InternalContracts/node_modules/assemblyscript/bin/asc:21:26)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
```

**Comment by MaxGraey** [comment]
Hmm, @dcodeIO It seems `offsetof<T>("prop")` not works if "prop" contains in superclass instead in subclass?

**Comment by FranklinWaller** [comment]
@MaxGraey Is there some value I can hard code for the time being? (Or find it in the source code)

**Comment by MaxGraey** [comment]
@FranklinWaller 
This hardcoded and not perfect version, but should work:

```ts
export function createTypedArray<TArray, T>(
  buffer: ArrayBuffer, 
  byteOffset: usize = 0, 
  length: i32 = 0
): TArray {
  if (buffer.byteLength - byteOffset > length * sizeof<T>()) {
    throw new RangeError("Invalid typed array length");
  }
  var arr = __alloc(offsetof<TArray>(), idof<TArray>());
  store<ArrayBuffer>(arr, buffer, 0); // buffer
  store<ArrayBuffer>(arr, changetype<usize>(buffer) + byteOffset, sizeof<usize>()); // dataStart
  store<i32>(arr, length * sizeof<T>(), sizeof<usize>() * 2); // dataLength
  return changetype<TArray>(arr);
}
```

https://webassembly.studio/?f=p4cytxy7tji

**Comment by FranklinWaller** [comment]
Thank you, appreciate it!
I would guess for example with Uint8Array, etc you would need to use it like:?
```
const arr = createTypedArray<Uint16Array, u16>(hash, 16, 24 / 2);
const arr2 = createTypedArray<Uint8Array, u8>(hash, 32, 24);
```

**Comment by FranklinWaller** [comment]
Works great! Thank you
