### ISSUE TITLE
asinit ERROR: Entry file 'asinit.ts' not found.

### ISSUE THREAD

**Issue by trusktr** [AssemblyScript/assemblyscript#615]
Not sure if I'm doing this right, but I wanted to try the dev branch to init a project:

```sh
❯ npx "AssemblyScript/assemblyscript#dev" asinit ./folder
ERROR: Entry file 'asinit.ts' not found.
    at Object.main (/Users/trusktr/.npm/_npx/29064/lib/node_modules/assemblyscript/cli/asc.js:389:25)
    at Object.<anonymous> (/Users/trusktr/.npm/_npx/29064/lib/node_modules/assemblyscript/bin/asc:21:26)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at findNodeScript.then.existing (/usr/local/lib/node_modules/npm/node_modules/libnpx/index.js:268:14)
```

and I get that error. Is that how I should run it?

**Comment by dcodeIO** [comment]
Haven't seen this specific `npx` syntax before. Are you sure that's how it works? If possible, I think you should add the dev branch as a dependency so you can use `asinit` normally.

**Comment by trusktr** [comment]
Yeah, I think that's one of the goals of `npx`, so that you can for example, `npx electron foo` from anywhere, without `npm installing` anything. Not sure about how to call specific files or binaries though, maybe I did that part wrong.

**Comment by trusktr** [comment]
Ah! Looks like I was missing a `-p`. So this works:

```sh
❯ npx -p "AssemblyScript/assemblyscript#dev" asinit .
```

**Comment by trusktr** [comment]
Sorry, I should've researched more first.
