### ISSUE TITLE
Error [AssertionError]: assertion failed

### ISSUE THREAD

**Issue by trusktr** [AssemblyScript/assemblyscript#645]
I'm getting an error without a helpful message like

```
{ Error [AssertionError]: assertion failed
    at t.assert (/Users/trusktr/src/infamous+glas/node_modules/as-pect/node_modules/assemblyscript/dist/assemblyscript.js:1:527996)
```

Note, I'm trying to run tests with as-pect. 

<details>
<summary>Here's the full output:</summary>

```
infamous+glas git:master ❯ npm test

> @ test /Users/trusktr/src/infamous+glas
> asp --reporter=SummaryTestReporter

       ___   _____                       __    
      /   | / ___/      ____  ___  _____/ /_   
     / /| | \__ \______/ __ \/ _ \/ ___/ __/   
    / ___ |___/ /_____/ /_/ /  __/ /__/ /_     
   /_/  |_/____/     / .___/\___/\___/\__/     
                    /_/                        

  ⚡AS-pect⚡ Test suite runner [1.0.0-beta]
  
[Log] Using configuration /Users/trusktr/src/infamous+glas/as-pect.config.js
[Log] Including files: src/as/**/*.spec.ts
[Log] Running tests that match: .*
[Log] Running groups that match: .*

✔ src/as/__tests__/example.spec.ts Pass: 1 / 1 Todo: 0 Time: 1.872ms
✔ src/as/glas/core/Layers.spec.ts Pass: 5 / 5 Todo: 0 Time: 2.56ms
There was a compilation error when trying to create the wasm binary for file: src/as/glas/math/Color.spec.ts.
{ Error [AssertionError]: assertion failed
    at t.assert (/Users/trusktr/src/infamous+glas/node_modules/as-pect/node_modules/assemblyscript/dist/assemblyscript.js:1:527996)
    at t.makeCallDirect (/Users/trusktr/src/infamous+glas/node_modules/as-pect/node_modules/assemblyscript/dist/assemblyscript.js:1:295254)
    at t.compileCallExpression (/Users/trusktr/src/infamous+glas/node_modules/as-pect/node_modules/assemblyscript/dist/assemblyscript.js:1:282523)
    at t.compileExpression (/Users/trusktr/src/infamous+glas/node_modules/as-pect/node_modules/assemblyscript/dist/assemblyscript.js:1:239421)
    at t.compileExpressionStatement (/Users/trusktr/src/infamous+glas/node_modules/as-pect/node_modules/assemblyscript/dist/assemblyscript.js:1:228716)
    at t.compileStatement (/Users/trusktr/src/infamous+glas/node_modules/as-pect/node_modules/assemblyscript/dist/assemblyscript.js:1:225068)
    at t.compileStatements (/Users/trusktr/src/infamous+glas/node_modules/as-pect/node_modules/assemblyscript/dist/assemblyscript.js:1:226077)
    at t.compileFunctionBody (/Users/trusktr/src/infamous+glas/node_modules/as-pect/node_modules/assemblyscript/dist/assemblyscript.js:1:215093)
    at t.compileFunction (/Users/trusktr/src/infamous+glas/node_modules/as-pect/node_modules/assemblyscript/dist/assemblyscript.js:1:217815)
    at t.compileFunctionExpression (/Users/trusktr/src/infamous+glas/node_modules/as-pect/node_modules/assemblyscript/dist/assemblyscript.js:1:300205) message: 'assertion failed' }
```

</details>

Here's reproduction:

```sh
git clone git@github.com:infamous/glas.git
cd glas
git checkout assemblyscript-issue-645
npm install
npm test
// error
```

The code in question is being called on this line:

https://github.com/infamous/glas/blob/bea0737beffb863239c9bd7149ec9a133a10f7f8/src/as/glas/math/Color.spec.ts#L34

And that `set` method is here:

https://github.com/infamous/glas/blob/assemblyscript-issue-645/src/as/glas/math/Color.ts#L230-L244

Any idea why the error?

**Comment by trusktr** [comment]
Updated the OP with a reproduction

**Comment by trusktr** [comment]
How can I give better error output (the above stack trace points one-line minified code)?

**Comment by jtenner** [comment]
You should gist the source code for the test suite so I can take a look at
it. Especially if it's related to aspect.

**Comment by trusktr** [comment]
@jtenner Hi, I updated the original post a reproduction:

The code in question is being called on this line:

https://github.com/infamous/glas/blob/bea0737beffb863239c9bd7149ec9a133a10f7f8/src/as/glas/math/Color.spec.ts#L34

And that set method is here:

https://github.com/infamous/glas/blob/assemblyscript-issue-645/src/as/glas/math/Color.ts#L230-L244

**Comment by trusktr** [comment]
@jtenner Thanks for looking into it!

**Comment by trusktr** [comment]
Alright, getting this error again, and I have another reproduction _without_ as-pect:

```
ERROR: AssertionError: assertion failed
    at name (/Users/trusktr/src/infamous+glas/node_modules/assemblyscript/dist/webpack:/assemblyscript/std/portable/index.js:180:1)
    at t.parameterTypes (/Users/trusktr/src/infamous+glas/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:6689:43)
    at t.resolveFunction [as compileCallExpression] (/Users/trusktr/src/infamous+glas/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:5863:36)
    at t.compileBinaryExpression [as compileExpression] (/Users/trusktr/src/infamous+glas/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:2758:21)
    at t.compileExpressionRetainType (/Users/trusktr/src/infamous+glas/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:2848:3)
    at Object.nonNullableType [as compileCall] (/Users/trusktr/src/infamous+glas/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/builtins.ts:2082:51)
    at t.makeMap [as compileCallExpressionBuiltin] (/Users/trusktr/src/infamous+glas/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:6032:9)
    at typeArguments [as compileCallExpression] (/Users/trusktr/src/infamous+glas/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:5772:40)
    at t.compileBinaryExpression [as compileExpression] (/Users/trusktr/src/infamous+glas/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:2758:21)
    at t.prototype [as compileExpressionStatement] (/Users/trusktr/src/infamous+glas/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:1960:3)
```

**reproduction:**

```sh
git clone git@github.com:infamous/glas.git
cd glas
git checkout assemblyscript-issue-645-2
npm install
# the following causes the build error:
asc src/as/glas/index.ts -b build/as/glas/untouched.wasm -t build/as/glas/untouched.wat --sourceMap --validate --debug
```

Maybe it's a different problem, just with similar error message.

**Comment by willemneal** [comment]
I just tried this out and this is something that I've had to grapple with when using generics.  The offending line in the assertion error is this:

`  at t.parameterTypes (/Users/trusktr/src/infamous+glas/node_modules/assemblyscript/dist/webpack:/assemblyscript/src/compiler.ts:6689:43)`.

Essentially you need to still provide the generic argument to test2.  I downloaded the code and tested it out and indeed adding the types solves the problem.  
```ts
        assert(a.test2<i32>(2), 'test2 failed')
        assert(!a.test2<string>(null), 'test2 failed')
```



This issue should serve as a request for better error messages for errors involving generics.

**Comment by trusktr** [comment]
I ran into this again. The error message isn't so helpful (same stack as above). Here's a reproduction:

```sh
git clone git@github.com:infamous/glas.git
cd glas
git checkout assemblyscript-issue-645-3
npm install
# the following causes the compile error:
npx asc src/as/glas/index.ts -b build/as/glas/untouched.wasm -t build/as/glas/untouched.wat --sourceMap --validate --debug
```

**Comment by trusktr** [comment]
@willemneal Ah, I see what you mean! 

The error message could be improved, f.e. "generic arg is missing" or "generic arg is required".

**Comment by trusktr** [comment]
Plus, I thought the generic arg was inferred from the callsite, like in regular TypeScript.

**Comment by trusktr** [comment]
@willemneal On the last reproduction, https://github.com/AssemblyScript/assemblyscript/issues/645#issuecomment-501537026, I was missing type args, and I added them but I'm still getting the error. Am I doing something wrong in checking the args in the conditional?

f.e.

```ts
	add<T>(object: T): this {
		let o: Object3D | null = null

		if (Array.isArray<Object3D>(object)) {
			for (let i = 0, l = object.length; i < l; i++) {
				o = object[i]

				// this conditional check is pointless, because we know the object will be
				// an Object3D here, but it is needed for type checking to work, and will be
				// optimized away in the compiler output.
				if (o instanceof Object3D) this.__add(o)
			}
		} else if (object instanceof Object3D) {
			this.__add(object)
		} else {
			throw new Error('Object3D.add: The argument should be an Object3D or Array<Object3D>')
		}

		return this
	}
```

**Comment by trusktr** [comment]
Based on this [playground example](https://www.assemblyscript.org/editor.html#IyFvcHRpbWl6ZT1zcGVlZCZydW50aW1lPXN0dWIKZnVuY3Rpb24gdGVzdDxUPihhOiBUKTogYm9vbGVhbiB7CgkJaWYgKGlzRmxvYXQ8VD4oYSkpCgkJCXJldHVybiB0cnVlCgkJZWxzZSBpZiAoaXNTdHJpbmc8VD4oYSkpCgkJCXJldHVybiB0cnVlCgoJCXJldHVybiBmYWxzZQp9CgovKiogQ2FsY3VsYXRlcyB0aGUgbi10aCBGaWJvbmFjY2kgbnVtYmVyLiAqLwpleHBvcnQgZnVuY3Rpb24gZmliKG46IGkzMik6IGJvb2wgewogIHJldHVybiB0ZXN0KHRydWUpCn0KIyFodG1sCjx0ZXh0YXJlYSBpZD0ib3V0cHV0IiBzdHlsZT0iaGVpZ2h0OiAxMDAlOyB3aWR0aDogMTAwJSIgcmVhZG9ubHk+PC90ZXh0YXJlYT4KPHNjcmlwdD4KbG9hZGVyLmluc3RhbnRpYXRlKG1vZHVsZV93YXNtLCB7IC8qIGltcG9ydHMgKi8gfSkKICAudGhlbigoeyBleHBvcnRzIH0pID0+IHsKICAgIGNvbnN0IG91dHB1dCA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdvdXRwdXQnKQogICAgZm9yIChsZXQgaSA9IDA7IGkgPD0gMTA7ICsraSkgewogICAgICBvdXRwdXQudmFsdWUgKz0gYGZpYigke2l9KSA9ICR7ZXhwb3J0cy5maWIoaSl9XG5gCiAgICB9CiAgfSkKPC9zY3JpcHQ+), it seems generic args are inferred nowadays.
