### ISSUE TITLE
Arrow function causes "Property 'foo' does not exist on type 'Bar#constructor'."

### ISSUE THREAD

**Issue by trusktr** [AssemblyScript/assemblyscript#661]
I've got some code like this, which is valid TS:

```ts
class Rotation {
  onChange(f: () => void): void {}
}

class Quaternion {
  setFromEuler(r: Rotation, u: boolean): void {}
}

class Object3D {
	readonly quaternion: Quaternion = new Quaternion()
	readonly rotation: Rotation = new Rotation()

	constructor() {
		this.rotation.onChange(this.onRotationChange)
	}

	onRotationChange: () => void = () => {
		this.quaternion.setFromEuler(this.rotation, false)
	}
}
```

but in trying to compile it I get the error

```
ERROR TS2339: Property 'quaternion' does not exist on type 'src/as/glas/core/Object3D/Object3D#constructor'.

                this.quaternion.setFromEuler(this.rotation, false)
        ~~~~~~~~~~
 in src/as/glas/core/Object3D.ts(196,7)

ERROR: Compile error
    at Object.main (/Users/trusktr/src/infamous+glas/node_modules/assemblyscript/cli/asc.js:492:21)
    at Object.<anonymous> (/Users/trusktr/src/infamous+glas/node_modules/assemblyscript/bin/asc:21:26)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
```

**Comment by trusktr** [comment]
Reproduction:

```
git clone git@github.com:infamous/glas.git
cd glas
git checkout assemblyscript-issue-661
npm install
# the following causes the error:
npx asc src/as/glas/index.ts -b build/as/glas/untouched.wasm -t build/as/glas/untouched.wat --sourceMap --validate --debug
```

**Comment by trusktr** [comment]
Made a WebAssembly.studio reproduction: https://webassembly.studio/?f=y1v80023ng

**Comment by trusktr** [comment]
I was able to work around the problem by doing the following

```ts
class Rotation {
  onChange(f: () => void): void {}
}

class Quaternion {
  setFromEuler(r: Rotation, u: boolean): void {}
}

let self: Object3D | null = null

class Object3D {
	readonly quaternion: Quaternion = new Quaternion()
	readonly rotation: Rotation = new Rotation()

	constructor() {
		self = this
		this.rotation.onChange(() => {
			self.onRotationChange()
		})
	}

	onRotationChange(): void {
		this.quaternion.setFromEuler(this.rotation, false)
	}
}
```

https://webassembly.studio/?f=1jhkys2da8w

**Comment by MaxGraey** [comment]
Closures doesn't support yet.
