### ISSUE TITLE
Optional parameters with initialiaser not working as expected

### ISSUE THREAD

**Issue by JamesMilnerUK** [AssemblyScript/assemblyscript#746]
It looks like optional parameters are not compiling at the moment. For example take the sample function from the documentation:

```typescript
export function foo(a?: i32 = 0): i32 {
	var b = a + 1;
	return b;
}
```

This results in:

```
ERROR TS1015: Parameter cannot have question mark and initializer.

 function foo(a?: i32 = 0): i32 {
              ~
 in assembly/index.ts(6,13)

ERROR: Parse error
    at parseBacklog (/home/james/Code/pixelmatch-wasm/node_modules/assemblyscript/cli/asc.js:451:23)
    at Object.main (/home/james/Code/pixelmatch-wasm/node_modules/assemblyscript/cli/asc.js:504:16)
    at Object.<anonymous> (/home/james/Code/pixelmatch-wasm/node_modules/assemblyscript/bin/asc:21:26)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
```

Is there something I'm missing here?

**Comment by dcodeIO** [comment]
Using both a question mark and an initializer is invalid syntax. Leave out the question mark and it should work as expected.

**Comment by JamesMilnerUK** [comment]
@dcodeIO okay, good to know. Would you like me to look into remove any examples that use both from the docs?

**Comment by dcodeIO** [comment]
Oh, yeah. on a first glimpse I found one and fixed it. Feel free to point out or fix the others :)

**Comment by JamesMilnerUK** [comment]
@dcodeIO if you think there are no other cases of this in the documentation then feel free to close :)

**Comment by dcodeIO** [comment]
Going to close then since I didn't find another one. If someone else does, feel free to send a PR on the docs repo :)

**Comment by MaxGraey** [comment]
> Using both a question mark and an initializer is invalid syntax. Leave out the question mark and it should work as expected.

I guess it should be valid for references becouse quesion mark for init field is just shorthand of `T | null` so `foo(str?: string = "I'm default string")` should be desugar to `foo(str: string | null = "I'm default string")`

**Comment by MaxGraey** [comment]
So `str?: string` is just equivalent to `str: string | null = null`

**Comment by DanielRX** [comment]
@MaxGraey does that mean for AS undefined is null?

**Comment by MaxGraey** [comment]
AS hasn't undefined. Only nulls
