### ISSUE TITLE
Print better compiler error for duplicate identifiers

### ISSUE THREAD

**Issue by MaxGraey** [AssemblyScript/assemblyscript#793]
```ts
class Foo {
  field: i32;
  field: i64;
}
const foo = new Foo();
```
But this should be valid:
```ts
class Foo {
  field: i32;
  static field: i64;
}
```

Expected compiler error:
```
Dublicate identifier 'field'
```
Actual:
```
ERROR: AssertionError: assertion failed
```

**Comment by DanielRX** [comment]
Me and @karzanbotani are currently working this fix now, is there a set way you want it to error?

This is the current message we have:
```ts
ERROR: AssertionError: Duplicate instance member: 'field' in file 'test.ts', line: 3 column: 15
    at assert (*/assemblyscript/std/portable/index.js:184:9)
    at Compiler.compileTopLevelStatement (*/assemblyscript/src/compiler.ts:1635:11)
    at Compiler.compileFile (*/assemblyscript/src/compiler.ts:759:12)
    at Compiler.compile (*/assemblyscript/src/compiler.ts:366:14)
    at Object.compileProgram (*/assemblyscript/src/index.ts:146:41)
    at stats.compileTime.measure (*/assemblyscript/cli/asc.js:591:31)
    at measure (*/assemblyscript/cli/asc.js:929:3)
    at Object.main (*/assemblyscript/cli/asc.js:590:26)
    at Object.<anonymous> (*/assemblyscript/bin/asc:21:26)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
```

**Comment by MaxGraey** [comment]
@DanielRX Great! But instead of `AssertionError` I guess it should be diagnostic error in `ASxxx` space like [`Duplicate decorator` here](https://github.com/AssemblyScript/assemblyscript/blob/master/src/diagnosticMessages.json#L18)

**Comment by DanielRX** [comment]
Noted, as a side point, we are going to add `static` and `instance` errors, so that it covers both cases.

**Comment by dcodeIO** [comment]
This is emitting a diagnostic with a related range now, indicating both the initial declaration and the duplicate one.
