### ISSUE TITLE
How to calculate remainder

### ISSUE THREAD

**Issue by ranbuch** [AssemblyScript/assemblyscript#807]
I'm trying to compile this code:
```javascript
export function changeAllChannels(data: Array<i8>, factor: i32): Array<i8> {
  let allMax = 0 as i8;
  for (let i = 0; i < data.length; i++) {
    allMax = max(allMax, data[i]);
  }
  for (let i = 0; i < data.length; i++) {
    if (factor > 1) {
      if (i % 4 == 3)
        continue;
      let max = (255 - allMax) - data[i];
      data[i] += max * (factor - 1);
    }
    else {
      if (i % 4 != 3)
        continue;
      data[i] *= factor;
      data[i] = min(data[i], 255);
    }
  }
  return data;
}
```

But this line:
```javascript
if (i % 4 == 3)
```
doesn't seems to compile.

I cannot find anything reference for `remainder` or `%` on the documentation.

BTW if you guys have any examples for images and pixels manipulations a link to those reference would be much appreciated.

**Comment by dcodeIO** [comment]
> `if (i % 4 == 3)` doesn't seems to compile.

This should compile just fine. Any error messages? Are you using current master from GitHub?

**Comment by MaxGraey** [comment]
This code shouldn't compile in latest AssemblyScript. It should print several errors:
```
ERROR AS200: Conversion from type 'i32' to 'i8' requires an explicit cast.

       data[i] += max * (factor - 1);
```
And that's right! If you don't see this messages probaly you have old compiler from `npm`. Make sure you install latest via `npm i --save-dev github:AssemblyScript/assemblyscript`

**Comment by MaxGraey** [comment]
> BTW if you guys have any examples for images and pixels manipulations a link to those reference would be much appreciated.

Did you see this?
1. https://github.com/AssemblyScript/assemblyscript/tree/master/examples/mandelbrot
2. https://github.com/AssemblyScript/assemblyscript/tree/master/examples/game-of-life

**Comment by ranbuch** [comment]
@dcodeIO Thank you for your answer.
This code runs fine:
```javascript
export function changeAllChannels(data: Array<i8>, factor: i32): Array<i8> {
  let allMax = 0 as i8;
  for (let i = 0; i < data.length; i++) {
    allMax = max(allMax, data[i]);
  }
  for (let i = 0; i < data.length; i++) {
    if (factor > 1) {
    }
  }
  return data;
}
```

While this code throws an error:
```javascript
export function changeAllChannels(data: Array<i8>, factor: i32): Array<i8> {
  let allMax = 0 as i8;
  for (let i = 0; i < data.length; i++) {
    allMax = max(allMax, data[i]);
  }
  for (let i = 0; i < data.length; i++) {
    if (factor > 1) {
      if (i % 4 == 3)
        continue;
    }
  }
  return data;
}
```

The error is:
```
[wasm-validator error in function $assembly/index/changeAllChannels] unexpected false: all break targets must be valid, on
[unreachable] (br $continue|1)
ERROR: Validate error
    at stats.validateTime.measure (C:\Users\ranbu\Documents\dev\assemblyscript\cli\asc.js:607:25)
    at measure (C:\Users\ranbu\Documents\dev\assemblyscript\cli\asc.js:929:3)
    at Object.main (C:\Users\ranbu\Documents\dev\assemblyscript\cli\asc.js:604:27)
    at Object.<anonymous> (C:\Users\ranbu\Documents\dev\assemblyscript\bin\asc:21:26)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
```

The only difference between the snippets is:
```javascript
if (i % 4 == 3)
        continue;
```

**Comment by ranbuch** [comment]
@MaxGraey 
> Did you see this

Those are great, Thanks!



> But that examples uses "low level style"

What do you mean by that?

**Comment by MaxGraey** [comment]
@dcodeIO Can confirm. Minimal example for reproduction:
```ts
export function test(b: bool): void {
  for (let i = 0; i < 10; i++) {
    if (b) {
      if (i % 4 == 3) {
        continue;
      }
    }
  }
}
```
Fiddle: https://webassembly.studio/?f=lglq8twabj

**Comment by dcodeIO** [comment]
Hmm, probably losing track of the continue label in nested blocks, when forking the flow.
