### ISSUE TITLE
Local tests fail

### ISSUE THREAD

**Issue by willemneal** [AssemblyScript/assemblyscript#858]
Currently master fails to load the compiler built by webpack.  And when I build locally the dist files are different and also fail.
```
willem@Godel-1473  ~/c/assemblyscript   master ●  node tests/compiler.js --help
/Users/willem/Research/wasm/assemblyscript/node_modules/binaryen/index.js:7
if(m){p=__dirname+"/";var la,ma;ia=function(c,f){var b=q(c);b||(la||(la=require("fs")),ma||(ma=require("path")),c=ma.normalize(c),b=la.readFileSync(c));return f?b:b.toString()};ka=function(c){c=ia(c,!0);c.buffer||(c=new Uint8Array(c));assert(c.buffer);return c};1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);process.on("uncaughtException",function(c){if(!(c instanceof na))throw c;});process.on("unhandledRejection",u);da=function(c){process.exit(c)};a.inspect=function(){return"[Emscripten Module object]"}}else if(ha)"undefined"!=


Error: Cannot find module './assemblyscript'
Require stack:
- /Users/willem/Research/wasm/assemblyscript/cli/asc.js
- /Users/willem/Research/wasm/assemblyscript/tests/compiler.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at eval (eval at <anonymous> (/Users/willem/Research/wasm/assemblyscript/cli/asc.js:46:26), <anonymous>:1:1)
    at /Users/willem/Research/wasm/assemblyscript/cli/asc.js:46:26
    at Object.<anonymous> (/Users/willem/Research/wasm/assemblyscript/cli/asc.js:54:3)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Module.load (internal/modules/cjs/loader.js:643:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/willem/Research/wasm/assemblyscript/cli/asc.js',
    '/Users/willem/Research/wasm/assemblyscript/tests/compiler.js'
  ]
}
```

**Comment by willemneal** [comment]
More info:
```ts
> assemblyscript@0.7.0 test:parser /Users/willem/Research/wasm/assemblyscript
> node tests/parser

/Users/willem/Research/wasm/assemblyscript/node_modules/binaryen/index.js:7
if(m){p=__dirname+"/";var la,ma;ia=function(c,f){var b=q(c);b||(la||(la=require("fs")),ma||(ma=require("path")),c=ma.normalize(c),b=la.readFileSync(c));return f?b:b.toString()};ka=function(c){c=ia(c,!0);c.buffer||(c=new Uint8Array(c));assert(c.buffer);return c};1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);process.on("uncaughtException",function(c){if(!(c instanceof na))throw c;});process.on("unhandledRejection",u);da=function(c){process.exit(c)};a.inspect=function(){return"[Emscripten Module object]"}}else if(ha)"undefined"!=


ReferenceError: _BinaryenWidenLowSVecI8x16ToVecI16x8 is not defined
    at /Users/willem/Research/wasm/assemblyscript/src/module.ts:194:3
    at Object.<anonymous> (/Users/willem/Research/wasm/assemblyscript/src/module.ts:202:2)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at Module.m._compile (/Users/willem/Research/wasm/assemblyscript/node_modules/ts-node/src/index.ts:435:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/willem/Research/wasm/assemblyscript/node_modules/ts-node/src/index.ts:438:12)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
```

**Comment by dcodeIO** [comment]
What's your binaryen.js version in `node_modules/`?

**Comment by willemneal** [comment]
Ah yeah it's the one from 09/14.  Thought I was up to date. It's working now.  Thanks!
