### ISSUE TITLE
Working With anyref and storing them using WebAssembly.Table

### ISSUE THREAD

**Issue by jtenner** [AssemblyScript/assemblyscript#885]
Obviously this is experimental stuff and upgrading my canvas library to use this technology is a risk, but currently, the documentation doesn't include anything on how to declare and use `WebAssembly.Table` objects to store `anyref` values. 

I'm just opening this as a tracking issue to help get documentation squared away, and help develop the one of the first libraries that actually uses anyref.

**Comment by jtenner** [comment]
The first problem I see is that passing arguments to an external function call is anything but ergonomic.

For my explaination, I will use this example:

```ts
  public translate(x: f64, y: f64): void {
    let args = createArray(2); // Reflect.apply() expects an array of arguments (filled with 0)
    Reflect.set(args, zero, changetype<anyref>(x)); // cant do this
    Reflect.set(args, one, changetype<anyref>(y)); // cant do this
    Reflect.apply(translate, getContext(this.__id), args);
  }
```

This code does not compile anyway because of this:

```
ERROR: concrete type expected
    at e.getTempLocal (C:\Users\jtenner\Desktop\projects\as2d\node_modules\assemblyscript\dist\webpack:\assemblyscript\src\flow.ts:308:63)
    at e.addScopedLocal (C:\Users\jtenner\Desktop\projects\as2d\node_modules\assemblyscript\dist\webpack:\assemblyscript\src\flow.ts:402:3)
    at r.DiagnosticCode [as compileVariableStatement] (C:\Users\jtenner\Desktop\projects\as2d\node_modules\assemblyscript\dist\webpack:\assemblyscript\src\compiler.ts:2554:15)
    at r.compileTryStatement [as compileStatement] (C:\Users\jtenner\Desktop\projects\as2d\node_modules\assemblyscript\dist\webpack:\assemblyscript\src\compiler.ts:1749:21)
    at r.compileStatements (C:\Users\jtenner\Desktop\projects\as2d\node_modules\assemblyscript\dist\webpack:\assemblyscript\src\compiler.ts:1795:5)
    at returnType [as compileFunctionBody] (C:\Users\jtenner\Desktop\projects\as2d\node_modules\assemblyscript\dist\webpack:\assemblyscript\src\compiler.ts:1135:41)
    at r.toNativeType [as compileFunction] (C:\Users\jtenner\Desktop\projects\as2d\node_modules\assemblyscript\dist\webpack:\assemblyscript\src\compiler.ts:1286:46)
    at r.INSTANCE [as makeCallDirect] (C:\Users\jtenner\Desktop\projects\as2d\node_modules\assemblyscript\dist\webpack:\assemblyscript\src\compiler.ts:6737:33)
    at r.skippedAutoreleases [as compileCallDirect] (C:\Users\jtenner\Desktop\projects\as2d\node_modules\assemblyscript\dist\webpack:\assemblyscript\src\compiler.ts:6211:14)
    at resolver [as compileCallExpression] (C:\Users\jtenner\Desktop\projects\as2d\node_modules\assemblyscript\dist\webpack:\assemblyscript\src\compiler.ts:5901:57)
```

An alternative would have to be creation of the anyref object by passing up values to javascript anyway.

```ts
createTwoArray(val1, val2): number[] {
  return [val1, val2];
}
```

This still isn't nice because I'm relying on JavaScript to assemble objects. This is unfortunate.

**Comment by jtenner** [comment]
Yeah. Each call into `Reflect.apply`, no matter how I optimize the array creation for reflection and property setting, will result in `O(n)` calls to the host.

Before, `as2d` was `O(p + 1)` where `p` was the number of strings that needed to be written to cache each frame.  I'm pretty sure that I will still need to do RPC decoding and encoding still.
