### ISSUE TITLE
Validate error should terminate asc

### ISSUE THREAD

**Issue by vird** [AssemblyScript/assemblyscript#894]
I'm trying compile obviously wrong code (changetype should be replaced with reinterpret)

    export function main(size_x:i32): f32 {
      return changetype<f32>(size_x);
    }

I run
`./node_modules/.bin/asc ./index.ts -b ./index.wasm -t ./index.wat --validate`

Result is expected.

    [wasm-validator error in function $index/main] 3 != 1: block with value and last element with value must match types, on
    [f32] [f32] (block (result f32)
     [i32] (local.get $0)
    ) ;; end block
    ERROR: Validate error
        at stats.validateTime.measure (/data/nodejs/experiments/as_hotreload_env/node_modules/assemblyscript/cli/asc.js:539:25)
        at measure (/data/nodejs/experiments/as_hotreload_env/node_modules/assemblyscript/cli/asc.js:846:3)
        at Object.main (/data/nodejs/experiments/as_hotreload_env/node_modules/assemblyscript/cli/asc.js:536:27)
        at Object.<anonymous> (/data/nodejs/experiments/as_hotreload_env/node_modules/assemblyscript/bin/asc:21:26)
        at Module._compile (internal/modules/cjs/loader.js:816:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
        at Module.load (internal/modules/cjs/loader.js:685:32)
        at Function.Module._load (internal/modules/cjs/loader.js:620:12)
        at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
        at internal/main/run_main_module.js:21:11

But asc should terminate after validation error.

**Comment by MaxGraey** [comment]
Definitely this should restrict during compilation and emit proper error
