### ISSUE TITLE
reinterpret f64 -> f32 or i32 cause Compile error

### ISSUE THREAD

**Issue by vird** [AssemblyScript/assemblyscript#895]
export function main(f: f64): f32 {
      return reinterpret<f32>(f);
    }

`./node_modules/.bin/asc ./index.ts -b ./index.wasm -t ./index.wat --validate`

    ERROR AS200: Conversion from type 'f64' to 'i32' requires an explicit cast.

       return reinterpret<f32>(f);
                               ~
     in index.ts(2,26)

    ERROR: Compile error
        at Object.main (/data/nodejs/experiments/as_hotreload_env/node_modules/assemblyscript/cli/asc.js:530:21)
        at Object.<anonymous> (/data/nodejs/experiments/as_hotreload_env/node_modules/assemblyscript/bin/asc:21:26)
        at Module._compile (internal/modules/cjs/loader.js:816:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
        at Module.load (internal/modules/cjs/loader.js:685:32)
        at Function.Module._load (internal/modules/cjs/loader.js:620:12)
        at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
        at internal/main/run_main_module.js:21:11

Related:

    export function main(f: f64): i32 {
      return reinterpret<i32>(f);
    }

causes

    ERROR AS200: Conversion from type 'f64' to 'f32' requires an explicit cast.

           return reinterpret<i32>(f);
                                   ~
     in index.ts(2,30)

    ERROR: Compile error
        at Object.main (/data/nodejs/experiments/as_hotreload_env/node_modules/assemblyscript/cli/asc.js:530:21)
        at Object.<anonymous> (/data/nodejs/experiments/as_hotreload_env/node_modules/assemblyscript/bin/asc:21:26)
        at Module._compile (internal/modules/cjs/loader.js:816:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
        at Module.load (internal/modules/cjs/loader.js:685:32)
        at Function.Module._load (internal/modules/cjs/loader.js:620:12)
        at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
        at internal/main/run_main_module.js:21:11

**Comment by MaxGraey** [comment]
That's expected behaviour. Generic and source types should have the same size and should be float and int or wise versa.

**Comment by vird** [comment]
How can I pass float (f64) from JS and round it to int inside AssemblyScript code?

**Comment by MaxGraey** [comment]
Just use normal casting:
```
let f: f64 = 2.5
let i1 = f as i32;
// or
let i2 = <i32>f;
```

**Comment by vird** [comment]
Thanks.
Probably reinterpret should have better error message if bit size is different.
