### ISSUE TITLE
webassembly.studio error

### ISSUE THREAD

**Issue by blooddy** [AssemblyScript/assemblyscript#99]
I tried to compile the old project and got an error
```
TypeError: Cannot read property 'or' of undefined
    at e.i64_or (https://rawgit.com/AssemblyScript/assemblyscript/master/dist/assemblyscript.js:1:338430)
    at e.setLocalWrapped (https://rawgit.com/AssemblyScript/assemblyscript/master/dist/assemblyscript.js:1:51475)
    at t.compileVariableStatement (https://rawgit.com/AssemblyScript/assemblyscript/master/dist/assemblyscript.js:1:184140)
    at t.compileStatement (https://rawgit.com/AssemblyScript/assemblyscript/master/dist/assemblyscript.js:1:175582)
    at t.compileStatements (https://rawgit.com/AssemblyScript/assemblyscript/master/dist/assemblyscript.js:1:176093)
    at t.compileBlockStatement (https://rawgit.com/AssemblyScript/assemblyscript/master/dist/assemblyscript.js:1:176364)
    at t.compileStatement (https://rawgit.com/AssemblyScript/assemblyscript/master/dist/assemblyscript.js:1:174858)
    at t.compileFunction (https://rawgit.com/AssemblyScript/assemblyscript/master/dist/assemblyscript.js:1:167822)
    at t.compileFunctionUsingTypeArguments (https://rawgit.com/AssemblyScript/assemblyscript/master/dist/assemblyscript.js:1:166370)
    at t.compileFunctionDeclaration (https://rawgit.com/AssemblyScript/assemblyscript/master/dist/assemblyscript.js:1:166167)

[error]: Cannot read property 'setOptimizeLevel' of undefined
```

**Comment by dcodeIO** [comment]
Trying to reproduce, but without success. Can you provide a bit more information?

**Comment by blooddy** [comment]
3 thousand lines of code =)
I'll try later

**Comment by blooddy** [comment]
https://webassembly.studio/?f=2ndydq43e0w

**Comment by dcodeIO** [comment]
Thanks, can confirm. Happens when there are more than 64 locals in a function.

**Comment by blooddy** [comment]
fix this plz =)
